export const MATCH_SCHEDULE = [
  // === MATCHDAY 1 ===
  // June 11, 2026 - Opening Day
  {
    id: 1,
    matchday: 1,
    group: 'A',
    date: '2026-06-11',
    time: '12:00',
    teamA: 'Mexico',
    teamB: 'Corea del Sur',
    venue: 'Estadio Azteca, Ciudad de Mexico',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 2,
    matchday: 1,
    group: 'A',
    date: '2026-06-11',
    time: '15:00',
    teamA: 'Sudafrica',
    teamB: 'Por definir',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 3,
    matchday: 1,
    group: 'B',
    date: '2026-06-11',
    time: '18:00',
    teamA: 'Canada',
    teamB: 'Suiza',
    venue: 'BMO Field, Toronto',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 4,
    matchday: 1,
    group: 'B',
    date: '2026-06-11',
    time: '21:00',
    teamA: 'Catar',
    teamB: 'Por definir',
    venue: 'BC Place, Vancouver',
    scoreA: null,
    scoreB: null,
  },
  // June 12, 2026
  {
    id: 5,
    matchday: 1,
    group: 'C',
    date: '2026-06-12',
    time: '12:00',
    teamA: 'Brasil',
    teamB: 'Marruecos',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 6,
    matchday: 1,
    group: 'C',
    date: '2026-06-12',
    time: '15:00',
    teamA: 'Haiti',
    teamB: 'Escocia',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 7,
    matchday: 1,
    group: 'D',
    date: '2026-06-12',
    time: '18:00',
    teamA: 'Estados Unidos',
    teamB: 'Paraguay',
    venue: 'MetLife Stadium, New York/New Jersey',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 8,
    matchday: 1,
    group: 'D',
    date: '2026-06-12',
    time: '21:00',
    teamA: 'Australia',
    teamB: 'Por definir',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  // June 13, 2026
  {
    id: 9,
    matchday: 1,
    group: 'E',
    date: '2026-06-13',
    time: '12:00',
    teamA: 'Alemania',
    teamB: 'Costa de Marfil',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 10,
    matchday: 1,
    group: 'E',
    date: '2026-06-13',
    time: '15:00',
    teamA: 'Ecuador',
    teamB: 'Curazao',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 11,
    matchday: 1,
    group: 'F',
    date: '2026-06-13',
    time: '18:00',
    teamA: 'Paises Bajos',
    teamB: 'Japon',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 12,
    matchday: 1,
    group: 'F',
    date: '2026-06-13',
    time: '21:00',
    teamA: 'Tunez',
    teamB: 'Por definir',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  // June 14, 2026
  {
    id: 13,
    matchday: 1,
    group: 'G',
    date: '2026-06-14',
    time: '12:00',
    teamA: 'Belgica',
    teamB: 'Egipto',
    venue: 'Lumen Field, Seattle',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 14,
    matchday: 1,
    group: 'G',
    date: '2026-06-14',
    time: '15:00',
    teamA: 'Iran',
    teamB: 'Nueva Zelanda',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 15,
    matchday: 1,
    group: 'H',
    date: '2026-06-14',
    time: '18:00',
    teamA: 'Espana',
    teamB: 'Arabia Saudita',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 16,
    matchday: 1,
    group: 'H',
    date: '2026-06-14',
    time: '21:00',
    teamA: 'Uruguay',
    teamB: 'Cabo Verde',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  // June 15, 2026
  {
    id: 17,
    matchday: 1,
    group: 'I',
    date: '2026-06-15',
    time: '12:00',
    teamA: 'Francia',
    teamB: 'Senegal',
    venue: 'Arrowhead Stadium, Kansas City',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 18,
    matchday: 1,
    group: 'I',
    date: '2026-06-15',
    time: '15:00',
    teamA: 'Noruega',
    teamB: 'Por definir',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 19,
    matchday: 1,
    group: 'J',
    date: '2026-06-15',
    time: '18:00',
    teamA: 'Argentina',
    teamB: 'Argelia',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 20,
    matchday: 1,
    group: 'J',
    date: '2026-06-15',
    time: '21:00',
    teamA: 'Austria',
    teamB: 'Jordania',
    venue: 'Estadio BBVA, Monterrey',
    scoreA: null,
    scoreB: null,
  },
  // June 16, 2026
  {
    id: 21,
    matchday: 1,
    group: 'K',
    date: '2026-06-16',
    time: '12:00',
    teamA: 'Portugal',
    teamB: 'Colombia',
    venue: 'Gillette Stadium, Boston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 22,
    matchday: 1,
    group: 'K',
    date: '2026-06-16',
    time: '15:00',
    teamA: 'Uzbekistan',
    teamB: 'Por definir',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 23,
    matchday: 1,
    group: 'L',
    date: '2026-06-16',
    time: '18:00',
    teamA: 'Inglaterra',
    teamB: 'Croacia',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 24,
    matchday: 1,
    group: 'L',
    date: '2026-06-16',
    time: '21:00',
    teamA: 'Ghana',
    teamB: 'Panama',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },

  // === MATCHDAY 2 ===
  // June 17, 2026
  {
    id: 25,
    matchday: 2,
    group: 'A',
    date: '2026-06-17',
    time: '12:00',
    teamA: 'Mexico',
    teamB: 'Sudafrica',
    venue: 'Estadio Azteca, Ciudad de Mexico',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 26,
    matchday: 2,
    group: 'A',
    date: '2026-06-17',
    time: '15:00',
    teamA: 'Corea del Sur',
    teamB: 'Por definir',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 27,
    matchday: 2,
    group: 'B',
    date: '2026-06-17',
    time: '18:00',
    teamA: 'Canada',
    teamB: 'Catar',
    venue: 'BMO Field, Toronto',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 28,
    matchday: 2,
    group: 'B',
    date: '2026-06-17',
    time: '21:00',
    teamA: 'Suiza',
    teamB: 'Por definir',
    venue: 'BC Place, Vancouver',
    scoreA: null,
    scoreB: null,
  },
  // June 18, 2026
  {
    id: 29,
    matchday: 2,
    group: 'C',
    date: '2026-06-18',
    time: '12:00',
    teamA: 'Brasil',
    teamB: 'Haiti',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 30,
    matchday: 2,
    group: 'C',
    date: '2026-06-18',
    time: '15:00',
    teamA: 'Marruecos',
    teamB: 'Escocia',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 31,
    matchday: 2,
    group: 'D',
    date: '2026-06-18',
    time: '18:00',
    teamA: 'Estados Unidos',
    teamB: 'Australia',
    venue: 'MetLife Stadium, New York/New Jersey',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 32,
    matchday: 2,
    group: 'D',
    date: '2026-06-18',
    time: '21:00',
    teamA: 'Paraguay',
    teamB: 'Por definir',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  // June 19, 2026
  {
    id: 33,
    matchday: 2,
    group: 'E',
    date: '2026-06-19',
    time: '12:00',
    teamA: 'Alemania',
    teamB: 'Ecuador',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 34,
    matchday: 2,
    group: 'E',
    date: '2026-06-19',
    time: '15:00',
    teamA: 'Costa de Marfil',
    teamB: 'Curazao',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 35,
    matchday: 2,
    group: 'F',
    date: '2026-06-19',
    time: '18:00',
    teamA: 'Paises Bajos',
    teamB: 'Tunez',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 36,
    matchday: 2,
    group: 'F',
    date: '2026-06-19',
    time: '21:00',
    teamA: 'Japon',
    teamB: 'Por definir',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  // June 20, 2026
  {
    id: 37,
    matchday: 2,
    group: 'G',
    date: '2026-06-20',
    time: '12:00',
    teamA: 'Belgica',
    teamB: 'Iran',
    venue: 'Lumen Field, Seattle',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 38,
    matchday: 2,
    group: 'G',
    date: '2026-06-20',
    time: '15:00',
    teamA: 'Egipto',
    teamB: 'Nueva Zelanda',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 39,
    matchday: 2,
    group: 'H',
    date: '2026-06-20',
    time: '18:00',
    teamA: 'Espana',
    teamB: 'Uruguay',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 40,
    matchday: 2,
    group: 'H',
    date: '2026-06-20',
    time: '21:00',
    teamA: 'Arabia Saudita',
    teamB: 'Cabo Verde',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  // June 21, 2026
  {
    id: 41,
    matchday: 2,
    group: 'I',
    date: '2026-06-21',
    time: '12:00',
    teamA: 'Francia',
    teamB: 'Noruega',
    venue: 'Arrowhead Stadium, Kansas City',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 42,
    matchday: 2,
    group: 'I',
    date: '2026-06-21',
    time: '15:00',
    teamA: 'Senegal',
    teamB: 'Por definir',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 43,
    matchday: 2,
    group: 'J',
    date: '2026-06-21',
    time: '18:00',
    teamA: 'Argentina',
    teamB: 'Austria',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 44,
    matchday: 2,
    group: 'J',
    date: '2026-06-21',
    time: '21:00',
    teamA: 'Argelia',
    teamB: 'Jordania',
    venue: 'Estadio BBVA, Monterrey',
    scoreA: null,
    scoreB: null,
  },
  // June 22, 2026
  {
    id: 45,
    matchday: 2,
    group: 'K',
    date: '2026-06-22',
    time: '12:00',
    teamA: 'Portugal',
    teamB: 'Uzbekistan',
    venue: 'Gillette Stadium, Boston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 46,
    matchday: 2,
    group: 'K',
    date: '2026-06-22',
    time: '15:00',
    teamA: 'Colombia',
    teamB: 'Por definir',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 47,
    matchday: 2,
    group: 'L',
    date: '2026-06-22',
    time: '18:00',
    teamA: 'Inglaterra',
    teamB: 'Ghana',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 48,
    matchday: 2,
    group: 'L',
    date: '2026-06-22',
    time: '21:00',
    teamA: 'Croacia',
    teamB: 'Panama',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },

  // === MATCHDAY 3 (simultaneous kickoffs per group) ===
  // June 23, 2026
  {
    id: 49,
    matchday: 3,
    group: 'A',
    date: '2026-06-23',
    time: '12:00',
    teamA: 'Corea del Sur',
    teamB: 'Sudafrica',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 50,
    matchday: 3,
    group: 'A',
    date: '2026-06-23',
    time: '12:00',
    teamA: 'Mexico',
    teamB: 'Por definir',
    venue: 'Estadio Azteca, Ciudad de Mexico',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 51,
    matchday: 3,
    group: 'B',
    date: '2026-06-23',
    time: '18:00',
    teamA: 'Suiza',
    teamB: 'Catar',
    venue: 'BC Place, Vancouver',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 52,
    matchday: 3,
    group: 'B',
    date: '2026-06-23',
    time: '18:00',
    teamA: 'Canada',
    teamB: 'Por definir',
    venue: 'BMO Field, Toronto',
    scoreA: null,
    scoreB: null,
  },
  // June 24, 2026
  {
    id: 53,
    matchday: 3,
    group: 'C',
    date: '2026-06-24',
    time: '12:00',
    teamA: 'Marruecos',
    teamB: 'Haiti',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 54,
    matchday: 3,
    group: 'C',
    date: '2026-06-24',
    time: '12:00',
    teamA: 'Brasil',
    teamB: 'Escocia',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 55,
    matchday: 3,
    group: 'D',
    date: '2026-06-24',
    time: '18:00',
    teamA: 'Paraguay',
    teamB: 'Australia',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 56,
    matchday: 3,
    group: 'D',
    date: '2026-06-24',
    time: '18:00',
    teamA: 'Estados Unidos',
    teamB: 'Por definir',
    venue: 'MetLife Stadium, New York/New Jersey',
    scoreA: null,
    scoreB: null,
  },
  // June 25, 2026
  {
    id: 57,
    matchday: 3,
    group: 'E',
    date: '2026-06-25',
    time: '12:00',
    teamA: 'Costa de Marfil',
    teamB: 'Ecuador',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 58,
    matchday: 3,
    group: 'E',
    date: '2026-06-25',
    time: '12:00',
    teamA: 'Alemania',
    teamB: 'Curazao',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 59,
    matchday: 3,
    group: 'F',
    date: '2026-06-25',
    time: '18:00',
    teamA: 'Japon',
    teamB: 'Tunez',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 60,
    matchday: 3,
    group: 'F',
    date: '2026-06-25',
    time: '18:00',
    teamA: 'Paises Bajos',
    teamB: 'Por definir',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  // June 26, 2026
  {
    id: 61,
    matchday: 3,
    group: 'G',
    date: '2026-06-26',
    time: '12:00',
    teamA: 'Egipto',
    teamB: 'Iran',
    venue: "Levi's Stadium, San Francisco",
    scoreA: null,
    scoreB: null,
  },
  {
    id: 62,
    matchday: 3,
    group: 'G',
    date: '2026-06-26',
    time: '12:00',
    teamA: 'Belgica',
    teamB: 'Nueva Zelanda',
    venue: 'Lumen Field, Seattle',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 63,
    matchday: 3,
    group: 'H',
    date: '2026-06-26',
    time: '18:00',
    teamA: 'Arabia Saudita',
    teamB: 'Uruguay',
    venue: 'Mercedes-Benz Stadium, Atlanta',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 64,
    matchday: 3,
    group: 'H',
    date: '2026-06-26',
    time: '18:00',
    teamA: 'Espana',
    teamB: 'Cabo Verde',
    venue: 'Hard Rock Stadium, Miami',
    scoreA: null,
    scoreB: null,
  },
  // June 27, 2026
  {
    id: 65,
    matchday: 3,
    group: 'I',
    date: '2026-06-27',
    time: '12:00',
    teamA: 'Senegal',
    teamB: 'Noruega',
    venue: 'AT&T Stadium, Dallas',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 66,
    matchday: 3,
    group: 'I',
    date: '2026-06-27',
    time: '12:00',
    teamA: 'Francia',
    teamB: 'Por definir',
    venue: 'Arrowhead Stadium, Kansas City',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 67,
    matchday: 3,
    group: 'J',
    date: '2026-06-27',
    time: '18:00',
    teamA: 'Argelia',
    teamB: 'Austria',
    venue: 'Estadio BBVA, Monterrey',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 68,
    matchday: 3,
    group: 'J',
    date: '2026-06-27',
    time: '18:00',
    teamA: 'Argentina',
    teamB: 'Jordania',
    venue: 'NRG Stadium, Houston',
    scoreA: null,
    scoreB: null,
  },
  // June 28, 2026
  {
    id: 69,
    matchday: 3,
    group: 'K',
    date: '2026-06-28',
    time: '12:00',
    teamA: 'Colombia',
    teamB: 'Uzbekistan',
    venue: 'Lincoln Financial Field, Philadelphia',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 70,
    matchday: 3,
    group: 'K',
    date: '2026-06-28',
    time: '12:00',
    teamA: 'Portugal',
    teamB: 'Por definir',
    venue: 'Gillette Stadium, Boston',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 71,
    matchday: 3,
    group: 'L',
    date: '2026-06-28',
    time: '18:00',
    teamA: 'Croacia',
    teamB: 'Ghana',
    venue: 'Estadio Akron, Guadalajara',
    scoreA: null,
    scoreB: null,
  },
  {
    id: 72,
    matchday: 3,
    group: 'L',
    date: '2026-06-28',
    time: '18:00',
    teamA: 'Inglaterra',
    teamB: 'Panama',
    venue: 'SoFi Stadium, Los Angeles',
    scoreA: null,
    scoreB: null,
  },
];
