// Player metadata for all World Cup 2026 sticker album players.
// Keys match exactly the player names from server/prisma/seed.js (excluding "Escudo" entries).

export const PLAYER_DATA = {
  // ===== CONCACAF =====

  // --- Mexico ---
  'Guillermo Ochoa': { position: 'GK', number: 13, birthYear: 1985 },
  'Jorge Sanchez': { position: 'DEF', number: 4, birthYear: 1997 },
  'Cesar Montes': { position: 'DEF', number: 3, birthYear: 1997 },
  'Johan Vasquez': { position: 'DEF', number: 5, birthYear: 1998 },
  'Jesus Gallardo': { position: 'DEF', number: 23, birthYear: 1994 },
  'Edson Alvarez': { position: 'MID', number: 4, birthYear: 1997 },
  'Luis Chavez': { position: 'MID', number: 14, birthYear: 1996 },
  'Orbelin Pineda': { position: 'MID', number: 10, birthYear: 1996 },
  'Carlos Rodriguez': { position: 'MID', number: 8, birthYear: 1997 },
  'Luis Romo': { position: 'MID', number: 7, birthYear: 1995 },
  'Erick Sanchez': { position: 'MID', number: 6, birthYear: 1999 },
  'Hirving Lozano': { position: 'FWD', number: 22, birthYear: 1995 },
  'Alexis Vega': { position: 'FWD', number: 11, birthYear: 1997 },
  'Roberto Alvarado': { position: 'MID', number: 20, birthYear: 1998 },
  'Uriel Antuna': { position: 'FWD', number: 17, birthYear: 1997 },
  'Diego Lainez': { position: 'MID', number: 18, birthYear: 2000 },
  'Raul Jimenez': { position: 'FWD', number: 9, birthYear: 1991 },
  'Henry Martin': { position: 'FWD', number: 21, birthYear: 1992 },
  'Santiago Gimenez': { position: 'FWD', number: 19, birthYear: 2001 },

  // --- Estados Unidos ---
  'Matt Turner': { position: 'GK', number: 1, birthYear: 1994 },
  'Sergino Dest': { position: 'DEF', number: 2, birthYear: 2000 },
  'Chris Richards': { position: 'DEF', number: 4, birthYear: 2000 },
  'Miles Robinson': { position: 'DEF', number: 12, birthYear: 1997 },
  'Antonee Robinson': { position: 'DEF', number: 5, birthYear: 1997 },
  'Tyler Adams': { position: 'MID', number: 4, birthYear: 1999 },
  'Weston McKennie': { position: 'MID', number: 8, birthYear: 1998 },
  'Yunus Musah': { position: 'MID', number: 6, birthYear: 2002 },
  'Giovanni Reyna': { position: 'MID', number: 7, birthYear: 2002 },
  'Brenden Aaronson': { position: 'MID', number: 11, birthYear: 2000 },
  'Malik Tillman': { position: 'MID', number: 14, birthYear: 2002 },
  'Christian Pulisic': { position: 'FWD', number: 10, birthYear: 1998 },
  'Timothy Weah': { position: 'FWD', number: 21, birthYear: 2000 },
  'Josh Sargent': { position: 'FWD', number: 9, birthYear: 2000 },
  'Ricardo Pepi': { position: 'FWD', number: 17, birthYear: 2003 },
  'Folarin Balogun': { position: 'FWD', number: 20, birthYear: 2001 },
  'Haji Wright': { position: 'FWD', number: 19, birthYear: 1998 },
  'Johnny Cardoso': { position: 'MID', number: 16, birthYear: 2001 },
  'Luca de la Torre': { position: 'MID', number: 15, birthYear: 1998 },

  // --- Canada ---
  'Maxime Crepeau': { position: 'GK', number: 16, birthYear: 1994 },
  'Alistair Johnston': { position: 'DEF', number: 2, birthYear: 1998 },
  'Kamal Miller': { position: 'DEF', number: 4, birthYear: 1997 },
  'Moise Bombito': { position: 'DEF', number: 5, birthYear: 2000 },
  'Sam Adekugbe': { position: 'DEF', number: 3, birthYear: 1995 },
  'Stephen Eustaquio': { position: 'MID', number: 7, birthYear: 1996 },
  'Ismael Kone': { position: 'MID', number: 8, birthYear: 2002 },
  'Mark-Anthony Kaye': { position: 'MID', number: 14, birthYear: 1994 },
  'Tajon Buchanan': { position: 'FWD', number: 11, birthYear: 1999 },
  'Jonathan David': { position: 'FWD', number: 20, birthYear: 2000 },
  'Alphonso Davies': { position: 'DEF', number: 19, birthYear: 2000 },
  'Cyle Larin': { position: 'FWD', number: 17, birthYear: 1995 },
  'Liam Millar': { position: 'FWD', number: 9, birthYear: 1999 },
  'Junior Hoilett': { position: 'FWD', number: 10, birthYear: 1990 },
  'Richie Laryea': { position: 'DEF', number: 22, birthYear: 1995 },
  'Jonathan Osorio': { position: 'MID', number: 21, birthYear: 1992 },
  'Jacob Shaffelburg': { position: 'FWD', number: 18, birthYear: 2000 },
  'Samuel Piette': { position: 'MID', number: 6, birthYear: 1994 },
  'Theo Corbeanu': { position: 'FWD', number: 15, birthYear: 2002 },

  // --- Panama ---
  'Orlando Mosquera': { position: 'GK', number: 1, birthYear: 1990 },
  'Michael Murillo': { position: 'DEF', number: 2, birthYear: 1996 },
  'Fidel Escobar': { position: 'DEF', number: 4, birthYear: 1995 },
  'Andres Andrade': { position: 'DEF', number: 3, birthYear: 1988 },
  'Eric Davis': { position: 'DEF', number: 15, birthYear: 1991 },
  'Adalberto Carrasquilla': { position: 'MID', number: 8, birthYear: 1998 },
  'Cristian Martinez': { position: 'MID', number: 10, birthYear: 1997 },
  'Jose Luis Rodriguez': { position: 'MID', number: 7, birthYear: 1994 },
  'Edgar Barcenas': { position: 'MID', number: 11, birthYear: 1993 },
  'Alberto Quintero': { position: 'FWD', number: 19, birthYear: 1987 },
  'Freddy Gondola': { position: 'FWD', number: 18, birthYear: 1994 },
  'Jose Fajardo': { position: 'FWD', number: 9, birthYear: 1997 },
  'Rolando Blackburn': { position: 'FWD', number: 20, birthYear: 1991 },
  'Cesar Yanis': { position: 'FWD', number: 17, birthYear: 2000 },
  'Ivan Anderson': { position: 'DEF', number: 5, birthYear: 1996 },
  'Anibal Godoy': { position: 'MID', number: 6, birthYear: 1990 },
  'Ernesto Walker': { position: 'DEF', number: 22, birthYear: 1997 },
  'Jiovany Ramos': { position: 'MID', number: 14, birthYear: 1999 },
  'Eduardo Guerrero': { position: 'FWD', number: 16, birthYear: 2001 },

  // --- Haiti ---
  'Alexandre Duval': { position: 'GK', number: 1, birthYear: 1998 },
  'Frantzdy Pierrot': { position: 'FWD', number: 9, birthYear: 1995 },
  'Carlens Arcus': { position: 'DEF', number: 2, birthYear: 1998 },
  'Kevin LaFrance': { position: 'DEF', number: 4, birthYear: 1990 },
  'Ricardo Ade': { position: 'DEF', number: 3, birthYear: 2001 },
  'Derrick Etienne Jr': { position: 'FWD', number: 11, birthYear: 1996 },
  'Melchie Dumornay': { position: 'MID', number: 10, birthYear: 2003 },
  'Bryan Alceus': { position: 'MID', number: 8, birthYear: 1999 },
  'Duckens Nazon': { position: 'FWD', number: 20, birthYear: 1994 },
  'Leverton Pierre': { position: 'MID', number: 6, birthYear: 1996 },
  'Danny Duval': { position: 'MID', number: 14, birthYear: 1997 },
  'Stephane Lambese': { position: 'DEF', number: 5, birthYear: 1993 },
  'Alex Jr Christian': { position: 'FWD', number: 17, birthYear: 1999 },
  'Ronaldo Damus': { position: 'FWD', number: 7, birthYear: 1999 },
  'Owayne Gordon': { position: 'DEF', number: 13, birthYear: 1995 },
  'Jean-Ricner Bellegarde': { position: 'MID', number: 16, birthYear: 1998 },
  'Steeven Saba': { position: 'DEF', number: 22, birthYear: 1997 },
  'Zachary Herivaux': { position: 'MID', number: 15, birthYear: 1999 },
  'Danley Jean Jacques': { position: 'DEF', number: 18, birthYear: 1993 },

  // --- Curazao ---
  'Eloy Room': { position: 'GK', number: 1, birthYear: 1989 },
  'Juninho Bacuna': { position: 'MID', number: 8, birthYear: 1997 },
  'Cuco Martina': { position: 'DEF', number: 2, birthYear: 1989 },
  'Darryl Lachman': { position: 'DEF', number: 3, birthYear: 1989 },
  'Shermaine Martina': { position: 'DEF', number: 4, birthYear: 1994 },
  'Leandro Bacuna': { position: 'MID', number: 6, birthYear: 1991 },
  'Michaell Tirpijn': { position: 'MID', number: 14, birthYear: 1998 },
  'Kenji Gorre': { position: 'FWD', number: 11, birthYear: 1994 },
  'Elson Hooi': { position: 'FWD', number: 9, birthYear: 1991 },
  'Rangelo Janga': { position: 'FWD', number: 7, birthYear: 1992 },
  'Brandley Kuwas': { position: 'FWD', number: 17, birthYear: 1992 },
  'Gervane Kastaneer': { position: 'FWD', number: 10, birthYear: 1996 },
  'Jairzinho Pieter': { position: 'MID', number: 15, birthYear: 1994 },
  'Charlison Benschop': { position: 'FWD', number: 20, birthYear: 1989 },
  'Jurien Gaari': { position: 'DEF', number: 5, birthYear: 1995 },
  'Vurnon Anita': { position: 'MID', number: 16, birthYear: 1989 },
  'Shadrach Victora': { position: 'MID', number: 18, birthYear: 1998 },
  'Quenten Martinus': { position: 'FWD', number: 22, birthYear: 1991 },
  'Jeremy de Nooijer': { position: 'MID', number: 19, birthYear: 1991 },

  // ===== CONMEBOL =====

  // --- Argentina ---
  'Emiliano Martinez': { position: 'GK', number: 23, birthYear: 1992 },
  'Nahuel Molina': { position: 'DEF', number: 26, birthYear: 1998 },
  'Cristian Romero': { position: 'DEF', number: 13, birthYear: 1998 },
  'Nicolas Otamendi': { position: 'DEF', number: 19, birthYear: 1988 },
  'Nicolas Tagliafico': { position: 'DEF', number: 3, birthYear: 1992 },
  'Rodrigo De Paul': { position: 'MID', number: 7, birthYear: 1994 },
  'Leandro Paredes': { position: 'MID', number: 5, birthYear: 1994 },
  'Enzo Fernandez': { position: 'MID', number: 24, birthYear: 2001 },
  'Alexis Mac Allister': { position: 'MID', number: 20, birthYear: 1998 },
  'Giovani Lo Celso': { position: 'MID', number: 18, birthYear: 1996 },
  'Exequiel Palacios': { position: 'MID', number: 14, birthYear: 1998 },
  'Lionel Messi': { position: 'FWD', number: 10, birthYear: 1987 },
  'Lautaro Martinez': { position: 'FWD', number: 22, birthYear: 1997 },
  'Julian Alvarez': { position: 'FWD', number: 9, birthYear: 2000 },
  'Paulo Dybala': { position: 'FWD', number: 21, birthYear: 1993 },
  'Alejandro Garnacho': { position: 'FWD', number: 17, birthYear: 2004 },
  'Nicolas Gonzalez': { position: 'FWD', number: 15, birthYear: 1998 },
  'Thiago Almada': { position: 'MID', number: 16, birthYear: 2001 },
  'Giuliano Simeone': { position: 'FWD', number: 11, birthYear: 2003 },

  // --- Brasil ---
  'Alisson': { position: 'GK', number: 1, birthYear: 1992 },
  'Danilo': { position: 'DEF', number: 2, birthYear: 1991 },
  'Marquinhos': { position: 'DEF', number: 4, birthYear: 1994 },
  'Gabriel Magalhaes': { position: 'DEF', number: 3, birthYear: 1997 },
  'Alex Telles': { position: 'DEF', number: 6, birthYear: 1992 },
  'Casemiro': { position: 'MID', number: 5, birthYear: 1992 },
  'Bruno Guimaraes': { position: 'MID', number: 16, birthYear: 1997 },
  'Lucas Paqueta': { position: 'MID', number: 10, birthYear: 1997 },
  'Andre': { position: 'MID', number: 18, birthYear: 2001 },
  'Joao Gomes': { position: 'MID', number: 15, birthYear: 2001 },
  'Douglas Luiz': { position: 'MID', number: 23, birthYear: 1998 },
  'Vinicius Jr': { position: 'FWD', number: 7, birthYear: 2000 },
  'Raphinha': { position: 'FWD', number: 11, birthYear: 1996 },
  'Rodrygo': { position: 'FWD', number: 21, birthYear: 2001 },
  'Richarlison': { position: 'FWD', number: 9, birthYear: 1997 },
  'Endrick': { position: 'FWD', number: 19, birthYear: 2006 },
  'Gabriel Martinelli': { position: 'FWD', number: 26, birthYear: 2001 },
  'Savinho': { position: 'FWD', number: 17, birthYear: 2004 },
  'Estevao': { position: 'FWD', number: 20, birthYear: 2007 },

  // --- Colombia ---
  'Camilo Vargas': { position: 'GK', number: 12, birthYear: 1989 },
  'Daniel Munoz': { position: 'DEF', number: 2, birthYear: 1996 },
  'Davinson Sanchez': { position: 'DEF', number: 23, birthYear: 1996 },
  'Yerry Mina': { position: 'DEF', number: 13, birthYear: 1994 },
  'Johan Mojica': { position: 'DEF', number: 17, birthYear: 1992 },
  'Wilmar Barrios': { position: 'MID', number: 5, birthYear: 1993 },
  'Mateus Uribe': { position: 'MID', number: 16, birthYear: 1991 },
  'James Rodriguez': { position: 'MID', number: 10, birthYear: 1991 },
  'Richard Rios': { position: 'MID', number: 6, birthYear: 2000 },
  'Jefferson Lerma': { position: 'MID', number: 14, birthYear: 1994 },
  'Kevin Castaño': { position: 'MID', number: 8, birthYear: 1998 },
  'Luis Diaz': { position: 'FWD', number: 7, birthYear: 1997 },
  'Rafael Santos Borre': { position: 'FWD', number: 19, birthYear: 1995 },
  'Luis Sinisterra': { position: 'FWD', number: 11, birthYear: 1999 },
  'Jhon Cordoba': { position: 'FWD', number: 9, birthYear: 1993 },
  'Miguel Borja': { position: 'FWD', number: 21, birthYear: 1993 },
  'Jhon Arias': { position: 'FWD', number: 18, birthYear: 1997 },
  'Jorge Carrascal': { position: 'MID', number: 20, birthYear: 1998 },
  'Juan Camilo Portilla': { position: 'DEF', number: 4, birthYear: 2001 },

  // --- Ecuador ---
  'Hernan Galindez': { position: 'GK', number: 1, birthYear: 1987 },
  'Angelo Preciado': { position: 'DEF', number: 2, birthYear: 1998 },
  'Felix Torres': { position: 'DEF', number: 3, birthYear: 1997 },
  'Piero Hincapie': { position: 'DEF', number: 4, birthYear: 2002 },
  'Pervis Estupinan': { position: 'DEF', number: 7, birthYear: 1998 },
  'Moises Caicedo': { position: 'MID', number: 23, birthYear: 2001 },
  'Carlos Gruezo': { position: 'MID', number: 8, birthYear: 1995 },
  'Alan Franco': { position: 'MID', number: 6, birthYear: 1998 },
  'Kendry Paez': { position: 'MID', number: 10, birthYear: 2007 },
  'Jeremy Sarmiento': { position: 'FWD', number: 17, birthYear: 2002 },
  'Gonzalo Plata': { position: 'FWD', number: 16, birthYear: 2000 },
  'Enner Valencia': { position: 'FWD', number: 13, birthYear: 1989 },
  'Michael Estrada': { position: 'FWD', number: 11, birthYear: 1996 },
  'Kevin Rodriguez': { position: 'FWD', number: 19, birthYear: 2000 },
  'John Yeboah': { position: 'FWD', number: 15, birthYear: 2000 },
  'Willian Pacho': { position: 'DEF', number: 22, birthYear: 2001 },
  'Jose Cifuentes': { position: 'MID', number: 5, birthYear: 1999 },
  'Angel Mena': { position: 'FWD', number: 14, birthYear: 1988 },
  'Joao Rojas': { position: 'FWD', number: 20, birthYear: 1989 },

  // --- Paraguay ---
  'Carlos Coronel': { position: 'GK', number: 1, birthYear: 1997 },
  'Alberto Espinola': { position: 'DEF', number: 4, birthYear: 1991 },
  'Gustavo Gomez': { position: 'DEF', number: 3, birthYear: 1993 },
  'Omar Alderete': { position: 'DEF', number: 6, birthYear: 1996 },
  'Junior Alonso': { position: 'DEF', number: 13, birthYear: 1993 },
  'Andres Cubas': { position: 'MID', number: 5, birthYear: 1996 },
  'Mathias Villasanti': { position: 'MID', number: 8, birthYear: 1997 },
  'Miguel Almiron': { position: 'MID', number: 10, birthYear: 1994 },
  'Julio Enciso': { position: 'FWD', number: 7, birthYear: 2004 },
  'Matias Rojas': { position: 'MID', number: 14, birthYear: 1995 },
  'Ramon Sosa': { position: 'FWD', number: 11, birthYear: 2000 },
  'Angel Romero': { position: 'FWD', number: 9, birthYear: 1992 },
  'Antonio Sanabria': { position: 'FWD', number: 19, birthYear: 1996 },
  'Adam Bareiro': { position: 'FWD', number: 20, birthYear: 1996 },
  'Gabriel Avalos': { position: 'FWD', number: 17, birthYear: 1994 },
  'Alex Arce': { position: 'FWD', number: 22, birthYear: 1996 },
  'Fabian Balbuena': { position: 'DEF', number: 2, birthYear: 1991 },
  'Damian Bobadilla': { position: 'MID', number: 16, birthYear: 2000 },
  'Hernan Perez': { position: 'MID', number: 15, birthYear: 1989 },

  // --- Uruguay ---
  'Sergio Rochet': { position: 'GK', number: 23, birthYear: 1993 },
  'Nahitan Nandez': { position: 'MID', number: 8, birthYear: 1995 },
  'Jose Maria Gimenez': { position: 'DEF', number: 2, birthYear: 1995 },
  'Ronald Araujo': { position: 'DEF', number: 4, birthYear: 1999 },
  'Mathias Olivera': { position: 'DEF', number: 16, birthYear: 1997 },
  'Federico Valverde': { position: 'MID', number: 15, birthYear: 1998 },
  'Rodrigo Bentancur': { position: 'MID', number: 6, birthYear: 1997 },
  'Manuel Ugarte': { position: 'MID', number: 5, birthYear: 2001 },
  'Nicolas De La Cruz': { position: 'MID', number: 10, birthYear: 1997 },
  'Giorgian De Arrascaeta': { position: 'MID', number: 20, birthYear: 1994 },
  'Facundo Pellistri': { position: 'FWD', number: 11, birthYear: 2001 },
  'Darwin Nunez': { position: 'FWD', number: 9, birthYear: 1999 },
  'Luis Suarez': { position: 'FWD', number: 7, birthYear: 1987 },
  'Maximiliano Araujo': { position: 'FWD', number: 17, birthYear: 2000 },
  'Agustin Canobbio': { position: 'FWD', number: 14, birthYear: 1998 },
  'Facundo Torres': { position: 'FWD', number: 22, birthYear: 2000 },
  'Matias Viña': { position: 'DEF', number: 3, birthYear: 1997 },
  'Sebastian Caceres': { position: 'DEF', number: 13, birthYear: 1999 },
  'Brian Rodriguez': { position: 'FWD', number: 18, birthYear: 2000 },

  // ===== UEFA =====

  // --- Francia ---
  'Mike Maignan': { position: 'GK', number: 16, birthYear: 1995 },
  'Jules Kounde': { position: 'DEF', number: 5, birthYear: 1998 },
  'Dayot Upamecano': { position: 'DEF', number: 4, birthYear: 1998 },
  'William Saliba': { position: 'DEF', number: 2, birthYear: 2001 },
  'Theo Hernandez': { position: 'DEF', number: 22, birthYear: 1997 },
  "N'Golo Kante": { position: 'MID', number: 13, birthYear: 1991 },
  'Aurelien Tchouameni': { position: 'MID', number: 8, birthYear: 2000 },
  'Eduardo Camavinga': { position: 'MID', number: 6, birthYear: 2002 },
  'Antoine Griezmann': { position: 'FWD', number: 7, birthYear: 1991 },
  'Adrien Rabiot': { position: 'MID', number: 14, birthYear: 1995 },
  'Youssouf Fofana': { position: 'MID', number: 19, birthYear: 1999 },
  'Kylian Mbappe': { position: 'FWD', number: 10, birthYear: 1998 },
  'Ousmane Dembele': { position: 'FWD', number: 11, birthYear: 1997 },
  'Marcus Thuram': { position: 'FWD', number: 15, birthYear: 1997 },
  'Randal Kolo Muani': { position: 'FWD', number: 12, birthYear: 1998 },
  'Bradley Barcola': { position: 'FWD', number: 20, birthYear: 2002 },
  'Warren Zaire-Emery': { position: 'MID', number: 18, birthYear: 2006 },
  'Michael Olise': { position: 'FWD', number: 17, birthYear: 2001 },
  'Khephren Thuram': { position: 'MID', number: 24, birthYear: 2001 },

  // --- Alemania ---
  'Manuel Neuer': { position: 'GK', number: 1, birthYear: 1986 },
  'Joshua Kimmich': { position: 'DEF', number: 6, birthYear: 1995 },
  'Antonio Rudiger': { position: 'DEF', number: 2, birthYear: 1993 },
  'Nico Schlotterbeck': { position: 'DEF', number: 4, birthYear: 1999 },
  'David Raum': { position: 'DEF', number: 3, birthYear: 1998 },
  'Robert Andrich': { position: 'MID', number: 21, birthYear: 1994 },
  'Pascal Gross': { position: 'MID', number: 15, birthYear: 1991 },
  'Jamal Musiala': { position: 'MID', number: 10, birthYear: 2003 },
  'Florian Wirtz': { position: 'MID', number: 17, birthYear: 2003 },
  'Leon Goretzka': { position: 'MID', number: 8, birthYear: 1995 },
  'Aleksandar Pavlovic': { position: 'MID', number: 23, birthYear: 2004 },
  'Leroy Sane': { position: 'FWD', number: 19, birthYear: 1996 },
  'Serge Gnabry': { position: 'FWD', number: 7, birthYear: 1995 },
  'Kai Havertz': { position: 'FWD', number: 9, birthYear: 1999 },
  'Niclas Fullkrug': { position: 'FWD', number: 11, birthYear: 1993 },
  'Chris Fuhrich': { position: 'FWD', number: 20, birthYear: 1998 },
  'Maximilian Beier': { position: 'FWD', number: 14, birthYear: 2002 },
  'Deniz Undav': { position: 'FWD', number: 13, birthYear: 1996 },
  'Benjamin Henrichs': { position: 'DEF', number: 18, birthYear: 1997 },

  // --- Espana ---
  'Unai Simon': { position: 'GK', number: 1, birthYear: 1997 },
  'Dani Carvajal': { position: 'DEF', number: 2, birthYear: 1992 },
  'Aymeric Laporte': { position: 'DEF', number: 14, birthYear: 1994 },
  'Robin Le Normand': { position: 'DEF', number: 24, birthYear: 1996 },
  'Marc Cucurella': { position: 'DEF', number: 3, birthYear: 1998 },
  'Rodri': { position: 'MID', number: 16, birthYear: 1996 },
  'Pedri': { position: 'MID', number: 8, birthYear: 2002 },
  'Gavi': { position: 'MID', number: 6, birthYear: 2004 },
  'Dani Olmo': { position: 'MID', number: 10, birthYear: 1998 },
  'Fabian Ruiz': { position: 'MID', number: 19, birthYear: 1996 },
  'Mikel Merino': { position: 'MID', number: 5, birthYear: 1996 },
  'Lamine Yamal': { position: 'FWD', number: 19, birthYear: 2007 },
  'Nico Williams': { position: 'FWD', number: 17, birthYear: 2002 },
  'Alvaro Morata': { position: 'FWD', number: 7, birthYear: 1992 },
  'Ferran Torres': { position: 'FWD', number: 11, birthYear: 2000 },
  'Alejandro Balde': { position: 'DEF', number: 20, birthYear: 2003 },
  'Fermin Lopez': { position: 'MID', number: 21, birthYear: 2003 },
  'Mikel Oyarzabal': { position: 'FWD', number: 9, birthYear: 1997 },
  'Pau Cubarsi': { position: 'DEF', number: 4, birthYear: 2007 },

  // --- Inglaterra ---
  'Jordan Pickford': { position: 'GK', number: 1, birthYear: 1994 },
  'Kyle Walker': { position: 'DEF', number: 2, birthYear: 1990 },
  'John Stones': { position: 'DEF', number: 5, birthYear: 1994 },
  'Marc Guehi': { position: 'DEF', number: 6, birthYear: 2000 },
  'Luke Shaw': { position: 'DEF', number: 3, birthYear: 1995 },
  'Declan Rice': { position: 'MID', number: 4, birthYear: 1999 },
  'Jude Bellingham': { position: 'MID', number: 10, birthYear: 2003 },
  'Kobbie Mainoo': { position: 'MID', number: 8, birthYear: 2005 },
  'Phil Foden': { position: 'MID', number: 11, birthYear: 2000 },
  'Cole Palmer': { position: 'MID', number: 20, birthYear: 2002 },
  'Angel Gomes': { position: 'MID', number: 14, birthYear: 2000 },
  'Bukayo Saka': { position: 'FWD', number: 7, birthYear: 2001 },
  'Anthony Gordon': { position: 'FWD', number: 17, birthYear: 2001 },
  'Harry Kane': { position: 'FWD', number: 9, birthYear: 1993 },
  'Ollie Watkins': { position: 'FWD', number: 19, birthYear: 1995 },
  'Morgan Gibbs-White': { position: 'MID', number: 16, birthYear: 2000 },
  'Trent Alexander-Arnold': { position: 'DEF', number: 18, birthYear: 1998 },
  'Jarrod Bowen': { position: 'FWD', number: 15, birthYear: 1996 },
  'Noni Madueke': { position: 'FWD', number: 22, birthYear: 2002 },

  // --- Portugal ---
  'Diogo Costa': { position: 'GK', number: 1, birthYear: 1999 },
  'Joao Cancelo': { position: 'DEF', number: 20, birthYear: 1994 },
  'Ruben Dias': { position: 'DEF', number: 4, birthYear: 1997 },
  'Antonio Silva': { position: 'DEF', number: 6, birthYear: 2003 },
  'Nuno Mendes': { position: 'DEF', number: 19, birthYear: 2002 },
  'Bruno Fernandes': { position: 'MID', number: 8, birthYear: 1994 },
  'Vitinha': { position: 'MID', number: 14, birthYear: 2000 },
  'Bernardo Silva': { position: 'MID', number: 10, birthYear: 1994 },
  'Joao Felix': { position: 'FWD', number: 11, birthYear: 1999 },
  'Joao Palhinha': { position: 'MID', number: 5, birthYear: 1995 },
  'Joao Neves': { position: 'MID', number: 18, birthYear: 2004 },
  'Cristiano Ronaldo': { position: 'FWD', number: 7, birthYear: 1985 },
  'Rafael Leao': { position: 'FWD', number: 17, birthYear: 1999 },
  'Goncalo Ramos': { position: 'FWD', number: 9, birthYear: 2001 },
  'Diogo Jota': { position: 'FWD', number: 21, birthYear: 1996 },
  'Pedro Neto': { position: 'FWD', number: 15, birthYear: 2000 },
  'Francisco Conceicao': { position: 'FWD', number: 22, birthYear: 2002 },
  'Goncalo Inacio': { position: 'DEF', number: 3, birthYear: 2001 },
  'Renato Sanches': { position: 'MID', number: 16, birthYear: 1997 },

  // --- Paises Bajos ---
  'Bart Verbruggen': { position: 'GK', number: 1, birthYear: 2002 },
  'Denzel Dumfries': { position: 'DEF', number: 22, birthYear: 1996 },
  'Virgil van Dijk': { position: 'DEF', number: 4, birthYear: 1991 },
  'Nathan Ake': { position: 'DEF', number: 5, birthYear: 1995 },
  'Ian Maatsen': { position: 'DEF', number: 3, birthYear: 2002 },
  'Frenkie de Jong': { position: 'MID', number: 21, birthYear: 1997 },
  'Ryan Gravenberch': { position: 'MID', number: 8, birthYear: 2002 },
  'Tijjani Reijnders': { position: 'MID', number: 14, birthYear: 1998 },
  'Xavi Simons': { position: 'MID', number: 10, birthYear: 2003 },
  'Teun Koopmeiners': { position: 'MID', number: 20, birthYear: 1998 },
  'Jerdy Schouten': { position: 'MID', number: 6, birthYear: 1997 },
  'Cody Gakpo': { position: 'FWD', number: 11, birthYear: 1999 },
  'Donyell Malen': { position: 'FWD', number: 18, birthYear: 1999 },
  'Memphis Depay': { position: 'FWD', number: 9, birthYear: 1994 },
  'Brian Brobbey': { position: 'FWD', number: 15, birthYear: 2002 },
  'Joshua Zirkzee': { position: 'FWD', number: 7, birthYear: 2001 },
  'Micky van de Ven': { position: 'DEF', number: 2, birthYear: 2001 },
  'Jurrien Timber': { position: 'DEF', number: 17, birthYear: 2001 },
  'Jeremie Frimpong': { position: 'DEF', number: 16, birthYear: 2000 },

  // --- Belgica ---
  'Koen Casteels': { position: 'GK', number: 1, birthYear: 1992 },
  'Timothy Castagne': { position: 'DEF', number: 21, birthYear: 1995 },
  'Wout Faes': { position: 'DEF', number: 4, birthYear: 1998 },
  'Jan Vertonghen': { position: 'DEF', number: 5, birthYear: 1987 },
  'Arthur Theate': { position: 'DEF', number: 3, birthYear: 2000 },
  'Kevin De Bruyne': { position: 'MID', number: 7, birthYear: 1991 },
  'Amadou Onana': { position: 'MID', number: 8, birthYear: 2001 },
  'Youri Tielemans': { position: 'MID', number: 14, birthYear: 1997 },
  'Arne Engels': { position: 'MID', number: 6, birthYear: 2003 },
  'Orel Mangala': { position: 'MID', number: 18, birthYear: 1998 },
  'Charles De Ketelaere': { position: 'FWD', number: 22, birthYear: 2001 },
  'Jeremy Doku': { position: 'FWD', number: 11, birthYear: 2002 },
  'Lois Openda': { position: 'FWD', number: 9, birthYear: 2000 },
  'Romelu Lukaku': { position: 'FWD', number: 10, birthYear: 1993 },
  'Leandro Trossard': { position: 'FWD', number: 15, birthYear: 1994 },
  'Johan Bakayoko': { position: 'FWD', number: 17, birthYear: 2003 },
  'Dodi Lukebakio': { position: 'FWD', number: 20, birthYear: 1997 },
  'Zeno Debast': { position: 'DEF', number: 2, birthYear: 2003 },
  'Aster Vranckx': { position: 'MID', number: 16, birthYear: 2002 },

  // --- Croacia ---
  'Dominik Livakovic': { position: 'GK', number: 1, birthYear: 1995 },
  'Josip Stanisic': { position: 'DEF', number: 2, birthYear: 1999 },
  'Josko Gvardiol': { position: 'DEF', number: 20, birthYear: 2002 },
  'Duje Caleta-Car': { position: 'DEF', number: 3, birthYear: 1996 },
  'Borna Sosa': { position: 'DEF', number: 19, birthYear: 1998 },
  'Luka Modric': { position: 'MID', number: 10, birthYear: 1985 },
  'Mateo Kovacic': { position: 'MID', number: 8, birthYear: 1994 },
  'Marcelo Brozovic': { position: 'MID', number: 11, birthYear: 1992 },
  'Mario Pasalic': { position: 'MID', number: 7, birthYear: 1995 },
  'Lovro Majer': { position: 'MID', number: 14, birthYear: 1998 },
  'Martin Baturina': { position: 'MID', number: 18, birthYear: 2003 },
  'Ivan Perisic': { position: 'FWD', number: 4, birthYear: 1989 },
  'Ante Budimir': { position: 'FWD', number: 16, birthYear: 1991 },
  'Andrej Kramaric': { position: 'FWD', number: 9, birthYear: 1991 },
  'Bruno Petkovic': { position: 'FWD', number: 6, birthYear: 1994 },
  'Luka Sucic': { position: 'MID', number: 15, birthYear: 2002 },
  'Igor Matanovic': { position: 'FWD', number: 22, birthYear: 2003 },
  'Josip Sutalo': { position: 'DEF', number: 5, birthYear: 2000 },
  'Marin Pongracic': { position: 'DEF', number: 13, birthYear: 1997 },

  // --- Suiza ---
  'Yann Sommer': { position: 'GK', number: 1, birthYear: 1988 },
  'Silvan Widmer': { position: 'DEF', number: 2, birthYear: 1993 },
  'Manuel Akanji': { position: 'DEF', number: 5, birthYear: 1995 },
  'Nico Elvedi': { position: 'DEF', number: 4, birthYear: 1996 },
  'Ricardo Rodriguez': { position: 'DEF', number: 13, birthYear: 1992 },
  'Granit Xhaka': { position: 'MID', number: 10, birthYear: 1992 },
  'Denis Zakaria': { position: 'MID', number: 6, birthYear: 1996 },
  'Remo Freuler': { position: 'MID', number: 8, birthYear: 1992 },
  'Xherdan Shaqiri': { position: 'MID', number: 23, birthYear: 1991 },
  'Ruben Vargas': { position: 'FWD', number: 15, birthYear: 1998 },
  'Fabian Rieder': { position: 'MID', number: 14, birthYear: 2002 },
  'Dan Ndoye': { position: 'FWD', number: 17, birthYear: 2000 },
  'Breel Embolo': { position: 'FWD', number: 7, birthYear: 1997 },
  'Zeki Amdouni': { position: 'FWD', number: 18, birthYear: 2000 },
  'Noah Okafor': { position: 'FWD', number: 9, birthYear: 2000 },
  'Steven Zuber': { position: 'MID', number: 16, birthYear: 1991 },
  'Edimilson Fernandes': { position: 'MID', number: 20, birthYear: 1996 },
  'Ardon Jashari': { position: 'MID', number: 19, birthYear: 2002 },
  'Filip Ugrinic': { position: 'MID', number: 11, birthYear: 1997 },

  // --- Austria ---
  'Patrick Pentz': { position: 'GK', number: 1, birthYear: 1997 },
  'Stefan Posch': { position: 'DEF', number: 2, birthYear: 1997 },
  'Kevin Danso': { position: 'DEF', number: 5, birthYear: 1998 },
  'Maximilian Wober': { position: 'DEF', number: 15, birthYear: 1998 },
  'Phillipp Mwene': { position: 'DEF', number: 3, birthYear: 1994 },
  'Konrad Laimer': { position: 'MID', number: 8, birthYear: 1997 },
  'Nicolas Seiwald': { position: 'MID', number: 6, birthYear: 2001 },
  'Florian Grillitsch': { position: 'MID', number: 14, birthYear: 1995 },
  'Marcel Sabitzer': { position: 'MID', number: 10, birthYear: 1994 },
  'Christoph Baumgartner': { position: 'MID', number: 19, birthYear: 1999 },
  'Romano Schmid': { position: 'MID', number: 23, birthYear: 2000 },
  'Marko Arnautovic': { position: 'FWD', number: 7, birthYear: 1989 },
  'Michael Gregoritsch': { position: 'FWD', number: 11, birthYear: 1994 },
  'Kevin Stöger': { position: 'MID', number: 18, birthYear: 1993 },
  'Patrick Wimmer': { position: 'FWD', number: 17, birthYear: 2001 },
  'Matthias Seidl': { position: 'MID', number: 20, birthYear: 2002 },
  'Flavius Daniliuc': { position: 'DEF', number: 4, birthYear: 2001 },
  'Phillipp Lienhart': { position: 'DEF', number: 13, birthYear: 1996 },
  'Alexander Prass': { position: 'DEF', number: 16, birthYear: 2001 },

  // --- Escocia ---
  'Angus Gunn': { position: 'GK', number: 1, birthYear: 1996 },
  'Anthony Ralston': { position: 'DEF', number: 2, birthYear: 1998 },
  'Grant Hanley': { position: 'DEF', number: 5, birthYear: 1991 },
  'John Souttar': { position: 'DEF', number: 4, birthYear: 1996 },
  'Andrew Robertson': { position: 'DEF', number: 3, birthYear: 1994 },
  'Scott McTominay': { position: 'MID', number: 8, birthYear: 1996 },
  'Callum McGregor': { position: 'MID', number: 14, birthYear: 1993 },
  'Billy Gilmour': { position: 'MID', number: 6, birthYear: 2001 },
  'John McGinn': { position: 'MID', number: 7, birthYear: 1994 },
  'Kenny McLean': { position: 'MID', number: 10, birthYear: 1992 },
  'Ryan Christie': { position: 'MID', number: 11, birthYear: 1995 },
  'Che Adams': { position: 'FWD', number: 9, birthYear: 1996 },
  'Lyndon Dykes': { position: 'FWD', number: 19, birthYear: 1995 },
  'Lawrence Shankland': { position: 'FWD', number: 20, birthYear: 1995 },
  'Ben Doak': { position: 'FWD', number: 17, birthYear: 2005 },
  'James Forrest': { position: 'FWD', number: 15, birthYear: 1991 },
  'Ryan Jack': { position: 'MID', number: 16, birthYear: 1992 },
  'Andy Irving': { position: 'MID', number: 18, birthYear: 2000 },
  'Lewis Morgan': { position: 'FWD', number: 22, birthYear: 1996 },

  // --- Noruega ---
  'Orjan Nyland': { position: 'GK', number: 1, birthYear: 1990 },
  'Marcus Holmgren Pedersen': { position: 'DEF', number: 2, birthYear: 2000 },
  'Leo Ostigard': { position: 'DEF', number: 4, birthYear: 1999 },
  'Andreas Hanche-Olsen': { position: 'DEF', number: 5, birthYear: 1997 },
  'Birger Meling': { position: 'DEF', number: 3, birthYear: 1994 },
  'Martin Odegaard': { position: 'MID', number: 8, birthYear: 1998 },
  'Sander Berge': { position: 'MID', number: 6, birthYear: 1998 },
  'Fredrik Aursnes': { position: 'MID', number: 14, birthYear: 1995 },
  'Antonio Nusa': { position: 'FWD', number: 11, birthYear: 2005 },
  'Oscar Bobb': { position: 'MID', number: 17, birthYear: 2003 },
  'Jens Petter Hauge': { position: 'FWD', number: 15, birthYear: 1999 },
  'Erling Haaland': { position: 'FWD', number: 9, birthYear: 2000 },
  'Alexander Sorloth': { position: 'FWD', number: 7, birthYear: 1995 },
  'Joshua King': { position: 'FWD', number: 10, birthYear: 1992 },
  'Mohamed Elyounoussi': { position: 'FWD', number: 22, birthYear: 1994 },
  'David Moller Wolfe': { position: 'DEF', number: 18, birthYear: 1999 },
  'Patrick Berg': { position: 'MID', number: 16, birthYear: 1997 },
  'Morten Thorsby': { position: 'MID', number: 20, birthYear: 1996 },
  'Julian Ryerson': { position: 'DEF', number: 13, birthYear: 1997 },

  // ===== CAF =====

  // --- Marruecos ---
  'Yassine Bounou': { position: 'GK', number: 1, birthYear: 1991 },
  'Achraf Hakimi': { position: 'DEF', number: 2, birthYear: 1998 },
  'Nayef Aguerd': { position: 'DEF', number: 5, birthYear: 1996 },
  'Romain Saiss': { position: 'DEF', number: 6, birthYear: 1990 },
  'Noussair Mazraoui': { position: 'DEF', number: 3, birthYear: 1997 },
  'Sofyan Amrabat': { position: 'MID', number: 4, birthYear: 1996 },
  'Azzedine Ounahi': { position: 'MID', number: 8, birthYear: 2000 },
  'Hakim Ziyech': { position: 'MID', number: 7, birthYear: 1993 },
  'Youssef En-Nesyri': { position: 'FWD', number: 19, birthYear: 1997 },
  'Ilias Akhomach': { position: 'FWD', number: 17, birthYear: 2004 },
  'Bilal El Khannouss': { position: 'MID', number: 14, birthYear: 2004 },
  'Brahim Diaz': { position: 'MID', number: 10, birthYear: 1999 },
  'Abde Ezzalzouli': { position: 'FWD', number: 11, birthYear: 2001 },
  'Soufiane Rahimi': { position: 'FWD', number: 15, birthYear: 1996 },
  'Amine Harit': { position: 'MID', number: 18, birthYear: 1997 },
  'Munir El Haddadi': { position: 'FWD', number: 9, birthYear: 1995 },
  'Zakaria Aboukhlal': { position: 'FWD', number: 20, birthYear: 2000 },
  'Adam Aznou': { position: 'DEF', number: 22, birthYear: 2006 },
  'Eliesse Ben Seghir': { position: 'MID', number: 23, birthYear: 2005 },

  // --- Senegal ---
  'Edouard Mendy': { position: 'GK', number: 16, birthYear: 1992 },
  'Kalidou Koulibaly': { position: 'DEF', number: 3, birthYear: 1991 },
  'Abdou Diallo': { position: 'DEF', number: 22, birthYear: 1996 },
  'Youssouf Sabaly': { position: 'DEF', number: 2, birthYear: 1993 },
  'Formose Mendy': { position: 'DEF', number: 4, birthYear: 2001 },
  'Idrissa Gueye': { position: 'MID', number: 5, birthYear: 1989 },
  'Nampalys Mendy': { position: 'MID', number: 6, birthYear: 1992 },
  'Pape Matar Sarr': { position: 'MID', number: 8, birthYear: 2002 },
  'Krepin Diatta': { position: 'FWD', number: 11, birthYear: 1999 },
  'Ismaila Sarr': { position: 'FWD', number: 7, birthYear: 1998 },
  'Iliman Ndiaye': { position: 'FWD', number: 17, birthYear: 2000 },
  'Nicolas Jackson': { position: 'FWD', number: 9, birthYear: 2001 },
  'Sadio Mane': { position: 'FWD', number: 10, birthYear: 1992 },
  'Habib Diarra': { position: 'MID', number: 14, birthYear: 2004 },
  'Boulaye Dia': { position: 'FWD', number: 19, birthYear: 1996 },
  'Lamine Camara': { position: 'MID', number: 18, birthYear: 2004 },
  'Mikayil Faye': { position: 'DEF', number: 13, birthYear: 2004 },
  'El Hadji Malick Diouf': { position: 'DEF', number: 20, birthYear: 2004 },
  'Cherif Ndiaye': { position: 'FWD', number: 15, birthYear: 1999 },

  // --- Egipto ---
  'Mohamed El Shenawy': { position: 'GK', number: 1, birthYear: 1988 },
  'Ahmed Fatouh': { position: 'DEF', number: 2, birthYear: 1992 },
  'Mohamed Abdel-Moneim': { position: 'DEF', number: 6, birthYear: 1999 },
  'Mahmoud Hamdy': { position: 'DEF', number: 4, birthYear: 1997 },
  'Ahmed Hegazi': { position: 'DEF', number: 5, birthYear: 1991 },
  'Mohamed Elneny': { position: 'MID', number: 8, birthYear: 1992 },
  'Tarek Hamed': { position: 'MID', number: 14, birthYear: 1988 },
  'Emam Ashour': { position: 'MID', number: 7, birthYear: 1997 },
  'Ibrahim Adel': { position: 'FWD', number: 15, birthYear: 2000 },
  'Mahmoud Trezeguet': { position: 'FWD', number: 11, birthYear: 1994 },
  'Mostafa Mohamed': { position: 'FWD', number: 9, birthYear: 1998 },
  'Mohamed Salah': { position: 'FWD', number: 10, birthYear: 1992 },
  'Omar Marmoush': { position: 'FWD', number: 17, birthYear: 1999 },
  'Ahmed Koka': { position: 'FWD', number: 19, birthYear: 1993 },
  'Marwan Hamdi': { position: 'FWD', number: 20, birthYear: 1999 },
  'Hussein El Shahat': { position: 'MID', number: 16, birthYear: 1991 },
  'Karim Fouad': { position: 'DEF', number: 3, birthYear: 1999 },
  'Mohamed Sherif': { position: 'FWD', number: 22, birthYear: 1996 },
  'Ahmed Sayed Zizo': { position: 'MID', number: 18, birthYear: 1996 },

  // --- Ghana ---
  'Lawrence Ati-Zigi': { position: 'GK', number: 1, birthYear: 1996 },
  'Tariq Lamptey': { position: 'DEF', number: 2, birthYear: 2000 },
  'Mohammed Salisu': { position: 'DEF', number: 4, birthYear: 1999 },
  'Alexander Djiku': { position: 'DEF', number: 3, birthYear: 1994 },
  'Gideon Mensah': { position: 'DEF', number: 5, birthYear: 1998 },
  'Thomas Partey': { position: 'MID', number: 5, birthYear: 1993 },
  'Mohammed Kudus': { position: 'MID', number: 10, birthYear: 2000 },
  'Elisha Owusu': { position: 'MID', number: 6, birthYear: 1997 },
  'Antoine Semenyo': { position: 'FWD', number: 11, birthYear: 2000 },
  'Ibrahim Sulemana': { position: 'MID', number: 14, birthYear: 2001 },
  'Fatawu Issahaku': { position: 'FWD', number: 17, birthYear: 2004 },
  'Jordan Ayew': { position: 'FWD', number: 9, birthYear: 1991 },
  'Inaki Williams': { position: 'FWD', number: 19, birthYear: 1994 },
  'Ernest Nuamah': { position: 'FWD', number: 15, birthYear: 2003 },
  'Abdul Samed': { position: 'MID', number: 8, birthYear: 2000 },
  'Osman Bukari': { position: 'FWD', number: 7, birthYear: 2000 },
  'Kamaldeen Sulemana': { position: 'FWD', number: 18, birthYear: 2002 },
  'Jerome Opoku': { position: 'DEF', number: 22, birthYear: 1999 },
  'Edmund Addo': { position: 'MID', number: 20, birthYear: 2000 },

  // --- Costa de Marfil ---
  'Yahia Fofana': { position: 'GK', number: 1, birthYear: 2000 },
  'Serge Aurier': { position: 'DEF', number: 2, birthYear: 1993 },
  'Odilon Kossounou': { position: 'DEF', number: 4, birthYear: 2001 },
  'Willy Boly': { position: 'DEF', number: 3, birthYear: 1991 },
  'Ghislain Konan': { position: 'DEF', number: 5, birthYear: 1996 },
  'Franck Kessie': { position: 'MID', number: 8, birthYear: 1996 },
  'Seko Fofana': { position: 'MID', number: 6, birthYear: 1995 },
  'Ibrahim Sangare': { position: 'MID', number: 14, birthYear: 1997 },
  'Jean-Philippe Krasso': { position: 'FWD', number: 9, birthYear: 1997 },
  'Nicolas Pepe': { position: 'FWD', number: 11, birthYear: 1995 },
  'Sebastien Haller': { position: 'FWD', number: 7, birthYear: 1994 },
  'Simon Adingra': { position: 'FWD', number: 17, birthYear: 2002 },
  'Oumar Diakite': { position: 'FWD', number: 18, birthYear: 2004 },
  'Karim Konate': { position: 'FWD', number: 15, birthYear: 2004 },
  'Christian Kouame': { position: 'FWD', number: 19, birthYear: 1997 },
  'Max-Alain Gradel': { position: 'FWD', number: 10, birthYear: 1987 },
  'Wilfried Singo': { position: 'DEF', number: 22, birthYear: 2000 },
  'Evan Ndicka': { position: 'DEF', number: 13, birthYear: 1999 },
  'Jeremie Boga': { position: 'FWD', number: 20, birthYear: 1997 },

  // --- Sudafrica ---
  'Ronwen Williams': { position: 'GK', number: 1, birthYear: 1992 },
  'Khuliso Mudau': { position: 'DEF', number: 2, birthYear: 1994 },
  'Siyanda Xulu': { position: 'DEF', number: 4, birthYear: 1993 },
  'Mothobi Mvala': { position: 'DEF', number: 6, birthYear: 1994 },
  'Aubrey Modiba': { position: 'MID', number: 3, birthYear: 1995 },
  'Teboho Mokoena': { position: 'MID', number: 8, birthYear: 1997 },
  'Themba Zwane': { position: 'MID', number: 10, birthYear: 1989 },
  'Ethan Brooks': { position: 'MID', number: 14, birthYear: 2003 },
  'Elias Mokwana': { position: 'FWD', number: 11, birthYear: 1999 },
  'Percy Tau': { position: 'FWD', number: 7, birthYear: 1994 },
  'Lyle Foster': { position: 'FWD', number: 9, birthYear: 2000 },
  'Iqraam Rayners': { position: 'FWD', number: 19, birthYear: 1996 },
  'Evidence Makgopa': { position: 'FWD', number: 17, birthYear: 2000 },
  'Oswin Appollis': { position: 'FWD', number: 15, birthYear: 2002 },
  'Bathusi Aubaas': { position: 'DEF', number: 5, birthYear: 2001 },
  'Thalente Mbatha': { position: 'MID', number: 16, birthYear: 2000 },
  'Relebohile Mofokeng': { position: 'FWD', number: 20, birthYear: 2006 },
  'Rushwin Dortley': { position: 'DEF', number: 13, birthYear: 2003 },
  'Patrick Maswanganyi': { position: 'MID', number: 18, birthYear: 1998 },

  // --- Tunez ---
  'Aymen Dahmen': { position: 'GK', number: 1, birthYear: 1997 },
  'Mohamed Drager': { position: 'DEF', number: 2, birthYear: 1996 },
  'Yassine Meriah': { position: 'DEF', number: 4, birthYear: 1993 },
  'Montassar Talbi': { position: 'DEF', number: 5, birthYear: 1998 },
  'Ali Abdi': { position: 'DEF', number: 3, birthYear: 1993 },
  'Aissa Laidouni': { position: 'MID', number: 8, birthYear: 1996 },
  'Ellyes Skhiri': { position: 'MID', number: 6, birthYear: 1995 },
  'Hannibal Mejbri': { position: 'MID', number: 7, birthYear: 2003 },
  'Youssef Msakni': { position: 'FWD', number: 10, birthYear: 1990 },
  'Naim Sliti': { position: 'FWD', number: 11, birthYear: 1992 },
  'Saifeddine Jaziri': { position: 'FWD', number: 9, birthYear: 1999 },
  'Anis Ben Slimane': { position: 'MID', number: 14, birthYear: 2001 },
  'Issam Jebali': { position: 'FWD', number: 19, birthYear: 1991 },
  'Seifeddine Jaziri': { position: 'FWD', number: 17, birthYear: 1999 },
  'Mohamed Ali Ben Romdhane': { position: 'MID', number: 15, birthYear: 1999 },
  'Ferjani Sassi': { position: 'MID', number: 20, birthYear: 1992 },
  'Ali Maaloul': { position: 'DEF', number: 13, birthYear: 1990 },
  'Wajdi Kechrida': { position: 'DEF', number: 22, birthYear: 1995 },
  'Ghaylane Chaalali': { position: 'MID', number: 18, birthYear: 1994 },

  // --- Argelia ---
  "Rais M'Bolhi": { position: 'GK', number: 1, birthYear: 1986 },
  'Youcef Atal': { position: 'DEF', number: 2, birthYear: 1996 },
  'Aissa Mandi': { position: 'DEF', number: 4, birthYear: 1991 },
  'Abdelkader Bedrane': { position: 'DEF', number: 5, birthYear: 1992 },
  'Ramy Bensebaini': { position: 'DEF', number: 3, birthYear: 1995 },
  'Ismael Bennacer': { position: 'MID', number: 6, birthYear: 1997 },
  'Nabil Bentaleb': { position: 'MID', number: 10, birthYear: 1994 },
  'Hichem Boudaoui': { position: 'MID', number: 8, birthYear: 1999 },
  'Amine Gouiri': { position: 'FWD', number: 11, birthYear: 2000 },
  'Said Benrahma': { position: 'FWD', number: 7, birthYear: 1995 },
  'Riyad Mahrez': { position: 'FWD', number: 17, birthYear: 1991 },
  'Islam Slimani': { position: 'FWD', number: 9, birthYear: 1988 },
  'Baghdad Bounedjah': { position: 'FWD', number: 19, birthYear: 1991 },
  'Yacine Brahimi': { position: 'FWD', number: 15, birthYear: 1990 },
  'Andy Delort': { position: 'FWD', number: 14, birthYear: 1991 },
  'Mohamed Amoura': { position: 'FWD', number: 18, birthYear: 2002 },
  'Adam Ounas': { position: 'FWD', number: 22, birthYear: 1996 },
  'Ibrahim Maza': { position: 'MID', number: 20, birthYear: 2006 },
  'Farhi Amine': { position: 'MID', number: 16, birthYear: 2002 },

  // --- Cabo Verde ---
  'Vozinha': { position: 'GK', number: 1, birthYear: 1986 },
  'Steven Fortes': { position: 'DEF', number: 4, birthYear: 1992 },
  'Roberto Lopes': { position: 'DEF', number: 3, birthYear: 1995 },
  'Logan Costa': { position: 'DEF', number: 5, birthYear: 2001 },
  'Dylan Tavares': { position: 'DEF', number: 2, birthYear: 1996 },
  'Kenny Rocha Santos': { position: 'MID', number: 8, birthYear: 1996 },
  'Jamiro Monteiro': { position: 'MID', number: 10, birthYear: 1993 },
  'Nuno Borges': { position: 'MID', number: 6, birthYear: 1996 },
  'Ryan Mendes': { position: 'FWD', number: 7, birthYear: 1990 },
  'Garry Rodrigues': { position: 'FWD', number: 11, birthYear: 1990 },
  'Julio Tavares': { position: 'FWD', number: 9, birthYear: 1988 },
  'Lisandro Semedo': { position: 'FWD', number: 14, birthYear: 1997 },
  'Gilson Benchimol': { position: 'FWD', number: 17, birthYear: 1998 },
  'Jovane Cabral': { position: 'FWD', number: 15, birthYear: 1998 },
  'Patrick Andrade': { position: 'MID', number: 16, birthYear: 1993 },
  'Willy Semedo': { position: 'MID', number: 18, birthYear: 1997 },
  'Djaniny': { position: 'FWD', number: 19, birthYear: 1991 },
  'Bebeto': { position: 'FWD', number: 20, birthYear: 1992 },
  'Stopira': { position: 'DEF', number: 13, birthYear: 1988 },

  // ===== AFC =====

  // --- Japon ---
  'Zion Suzuki': { position: 'GK', number: 1, birthYear: 2002 },
  'Hiroki Sakai': { position: 'DEF', number: 2, birthYear: 1990 },
  'Ko Itakura': { position: 'DEF', number: 4, birthYear: 1997 },
  'Takehiro Tomiyasu': { position: 'DEF', number: 3, birthYear: 1998 },
  'Miki Yamane': { position: 'DEF', number: 5, birthYear: 1993 },
  'Wataru Endo': { position: 'MID', number: 6, birthYear: 1993 },
  'Hidemasa Morita': { position: 'MID', number: 8, birthYear: 1995 },
  'Daichi Kamada': { position: 'MID', number: 14, birthYear: 1996 },
  'Takefusa Kubo': { position: 'FWD', number: 7, birthYear: 2001 },
  'Ritsu Doan': { position: 'FWD', number: 11, birthYear: 1998 },
  'Kaoru Mitoma': { position: 'FWD', number: 10, birthYear: 1997 },
  'Takumi Minamino': { position: 'FWD', number: 15, birthYear: 1995 },
  'Ayase Ueda': { position: 'FWD', number: 9, birthYear: 1998 },
  'Kyogo Furuhashi': { position: 'FWD', number: 19, birthYear: 1995 },
  'Daizen Maeda': { position: 'FWD', number: 17, birthYear: 1997 },
  'Ao Tanaka': { position: 'MID', number: 16, birthYear: 1998 },
  'Keito Nakamura': { position: 'FWD', number: 13, birthYear: 2000 },
  'Koji Miyoshi': { position: 'FWD', number: 22, birthYear: 1997 },
  'Yuki Soma': { position: 'FWD', number: 18, birthYear: 1997 },

  // --- Corea del Sur ---
  'Kim Seung-gyu': { position: 'GK', number: 1, birthYear: 1990 },
  'Kim Moon-hwan': { position: 'DEF', number: 2, birthYear: 1995 },
  'Kim Min-jae': { position: 'DEF', number: 3, birthYear: 1996 },
  'Kim Young-gwon': { position: 'DEF', number: 4, birthYear: 1990 },
  'Kim Jin-su': { position: 'DEF', number: 5, birthYear: 1992 },
  'Hwang In-beom': { position: 'MID', number: 6, birthYear: 1996 },
  'Jung Woo-young': { position: 'MID', number: 8, birthYear: 1989 },
  'Lee Jae-sung': { position: 'MID', number: 14, birthYear: 1992 },
  'Lee Kang-in': { position: 'MID', number: 10, birthYear: 2001 },
  'Hwang Hee-chan': { position: 'FWD', number: 11, birthYear: 1996 },
  'Son Heung-min': { position: 'FWD', number: 7, birthYear: 1992 },
  'Cho Gue-sung': { position: 'FWD', number: 9, birthYear: 1998 },
  'Lee Seung-woo': { position: 'FWD', number: 17, birthYear: 1998 },
  'Bae Jun-ho': { position: 'MID', number: 15, birthYear: 2002 },
  'Jeong Sang-bin': { position: 'FWD', number: 19, birthYear: 2002 },
  'Hong Hyun-seok': { position: 'FWD', number: 20, birthYear: 1999 },
  'Park Yong-woo': { position: 'MID', number: 16, birthYear: 2003 },
  'Oh Hyeon-gyu': { position: 'FWD', number: 22, birthYear: 2001 },
  'Yang Hyun-jun': { position: 'FWD', number: 18, birthYear: 2003 },

  // --- Australia ---
  'Mathew Ryan': { position: 'GK', number: 1, birthYear: 1992 },
  'Nathaniel Atkinson': { position: 'DEF', number: 2, birthYear: 1999 },
  'Harry Souttar': { position: 'DEF', number: 4, birthYear: 1998 },
  'Kye Rowles': { position: 'DEF', number: 3, birthYear: 1998 },
  'Aziz Behich': { position: 'DEF', number: 5, birthYear: 1990 },
  'Jackson Irvine': { position: 'MID', number: 8, birthYear: 1993 },
  'Aaron Mooy': { position: 'MID', number: 6, birthYear: 1990 },
  'Cameron Devlin': { position: 'MID', number: 14, birthYear: 1998 },
  'Riley McGree': { position: 'MID', number: 10, birthYear: 1998 },
  'Craig Goodwin': { position: 'FWD', number: 11, birthYear: 1991 },
  'Keanu Baccus': { position: 'MID', number: 16, birthYear: 1998 },
  'Mitch Duke': { position: 'FWD', number: 7, birthYear: 1991 },
  'Jamie Maclaren': { position: 'FWD', number: 9, birthYear: 1993 },
  'Kusini Yengi': { position: 'FWD', number: 19, birthYear: 1999 },
  'Garang Kuol': { position: 'FWD', number: 22, birthYear: 2004 },
  'Marco Tilio': { position: 'FWD', number: 17, birthYear: 2001 },
  "Aiden O'Neill": { position: 'MID', number: 20, birthYear: 1998 },
  'Connor Metcalfe': { position: 'MID', number: 15, birthYear: 2000 },
  'Martin Boyle': { position: 'FWD', number: 18, birthYear: 1993 },

  // --- Arabia Saudita ---
  'Mohammed Al Owais': { position: 'GK', number: 1, birthYear: 1991 },
  'Sultan Al-Ghanam': { position: 'DEF', number: 2, birthYear: 1993 },
  'Ali Al-Bulayhi': { position: 'DEF', number: 4, birthYear: 1989 },
  'Abdulelah Al-Amri': { position: 'DEF', number: 3, birthYear: 1997 },
  'Yasser Al-Shahrani': { position: 'DEF', number: 13, birthYear: 1992 },
  'Mohamed Kanno': { position: 'MID', number: 8, birthYear: 1994 },
  'Abdulellah Al-Malki': { position: 'MID', number: 6, birthYear: 1994 },
  'Saud Abdulhamid': { position: 'DEF', number: 5, birthYear: 1999 },
  'Salem Al-Dawsari': { position: 'FWD', number: 10, birthYear: 1991 },
  'Firas Al-Buraikan': { position: 'FWD', number: 7, birthYear: 2000 },
  'Abdullah Al-Hamdan': { position: 'FWD', number: 11, birthYear: 1999 },
  'Saleh Al-Shehri': { position: 'FWD', number: 9, birthYear: 1993 },
  'Nasser Al-Dawsari': { position: 'MID', number: 14, birthYear: 1998 },
  'Nawaf Al-Abed': { position: 'MID', number: 15, birthYear: 1990 },
  'Hassan Al-Tambakti': { position: 'DEF', number: 22, birthYear: 1999 },
  'Ali Al-Hassan': { position: 'MID', number: 16, birthYear: 1997 },
  'Ayman Yahya': { position: 'FWD', number: 19, birthYear: 2003 },
  'Abdullah Madu': { position: 'DEF', number: 20, birthYear: 1993 },
  'Turki Al-Ammar': { position: 'GK', number: 21, birthYear: 1997 },

  // --- Iran ---
  'Alireza Beiranvand': { position: 'GK', number: 1, birthYear: 1992 },
  'Sadegh Moharrami': { position: 'DEF', number: 2, birthYear: 1996 },
  'Morteza Pouraliganji': { position: 'DEF', number: 5, birthYear: 1992 },
  'Shoja Khalilzadeh': { position: 'DEF', number: 4, birthYear: 1989 },
  'Ehsan Hajsafi': { position: 'DEF', number: 3, birthYear: 1990 },
  'Saeid Ezatolahi': { position: 'MID', number: 6, birthYear: 1996 },
  'Ahmad Nourollahi': { position: 'MID', number: 8, birthYear: 1993 },
  'Ali Gholizadeh': { position: 'MID', number: 14, birthYear: 1996 },
  'Mehdi Taremi': { position: 'FWD', number: 9, birthYear: 1992 },
  'Sardar Azmoun': { position: 'FWD', number: 11, birthYear: 1995 },
  'Alireza Jahanbakhsh': { position: 'FWD', number: 7, birthYear: 1993 },
  'Karim Ansarifard': { position: 'FWD', number: 10, birthYear: 1990 },
  'Ali Karimi': { position: 'MID', number: 17, birthYear: 1994 },
  'Omid Noorafkan': { position: 'DEF', number: 15, birthYear: 1997 },
  'Milad Sarlak': { position: 'MID', number: 16, birthYear: 1995 },
  'Allahyar Sayyadmanesh': { position: 'FWD', number: 19, birthYear: 2001 },
  'Mehdi Ghayedi': { position: 'FWD', number: 22, birthYear: 1998 },
  'Vahid Amiri': { position: 'MID', number: 13, birthYear: 1988 },
  'Rouzbeh Cheshmi': { position: 'DEF', number: 20, birthYear: 1993 },

  // --- Catar ---
  'Saad Al Sheeb': { position: 'GK', number: 1, birthYear: 1990 },
  'Pedro Miguel': { position: 'DEF', number: 2, birthYear: 1990 },
  'Bassam Al-Rawi': { position: 'DEF', number: 3, birthYear: 1997 },
  'Abdelkarim Hassan': { position: 'DEF', number: 4, birthYear: 1993 },
  'Homam Ahmed': { position: 'DEF', number: 5, birthYear: 1999 },
  'Hassan Al-Haydos': { position: 'FWD', number: 10, birthYear: 1990 },
  'Karim Boudiaf': { position: 'MID', number: 6, birthYear: 1990 },
  'Abdulaziz Hatem': { position: 'MID', number: 8, birthYear: 1990 },
  'Akram Afif': { position: 'FWD', number: 11, birthYear: 1996 },
  'Almoez Ali': { position: 'FWD', number: 9, birthYear: 1996 },
  'Mohammed Muntari': { position: 'FWD', number: 7, birthYear: 1993 },
  'Ismaeel Mohammad': { position: 'MID', number: 14, birthYear: 1990 },
  'Yusuf Abdurisag': { position: 'MID', number: 15, birthYear: 1997 },
  'Musab Kheder': { position: 'DEF', number: 13, birthYear: 1997 },
  'Ahmed Alaaeldin': { position: 'MID', number: 17, birthYear: 1993 },
  'Assim Madibo': { position: 'MID', number: 16, birthYear: 1996 },
  'Sultan Al-Brake': { position: 'MID', number: 18, birthYear: 1995 },
  'Ali Asad': { position: 'FWD', number: 19, birthYear: 1998 },
  'Hashim Ali': { position: 'DEF', number: 20, birthYear: 2001 },

  // --- Jordania ---
  'Yazeed Abulaila': { position: 'GK', number: 1, birthYear: 1996 },
  'Salem Al-Ajalin': { position: 'DEF', number: 2, birthYear: 1993 },
  'Anas Bani-Yaseen': { position: 'DEF', number: 4, birthYear: 1990 },
  'Abdallah Nasib': { position: 'DEF', number: 5, birthYear: 1992 },
  'Ehsan Haddad': { position: 'DEF', number: 3, birthYear: 1995 },
  'Baha Faisal': { position: 'MID', number: 8, birthYear: 1994 },
  'Nizar Al-Rashdan': { position: 'MID', number: 6, birthYear: 1999 },
  'Mousa Al-Taamari': { position: 'FWD', number: 7, birthYear: 1997 },
  'Yazan Al-Naimat': { position: 'FWD', number: 9, birthYear: 2000 },
  'Hamza Al-Dardour': { position: 'FWD', number: 10, birthYear: 1990 },
  'Musa Mustafa': { position: 'MID', number: 14, birthYear: 1995 },
  'Ali Olwan': { position: 'FWD', number: 11, birthYear: 1997 },
  'Ahmad Ersan': { position: 'MID', number: 16, birthYear: 1988 },
  'Oday Dabbagh': { position: 'FWD', number: 17, birthYear: 1998 },
  'Tareq Khattab': { position: 'DEF', number: 15, birthYear: 1996 },
  'Mahmoud Mardi': { position: 'MID', number: 18, birthYear: 1995 },
  'Youssef Rawashdeh': { position: 'DEF', number: 13, birthYear: 2000 },
  'Mohammed Abu Zraiq': { position: 'MID', number: 20, birthYear: 1999 },
  'Amer Shafi': { position: 'GK', number: 22, birthYear: 1988 },

  // --- Uzbekistan ---
  'Utkir Yusupov': { position: 'GK', number: 1, birthYear: 1999 },
  'Husniddin Aliqulov': { position: 'DEF', number: 2, birthYear: 1999 },
  'Abdukodir Khusanov': { position: 'DEF', number: 4, birthYear: 2004 },
  'Jermejev Nurmatov': { position: 'DEF', number: 5, birthYear: 1999 },
  'Davron Khashimov': { position: 'DEF', number: 3, birthYear: 2001 },
  'Oston Urunov': { position: 'MID', number: 8, birthYear: 1995 },
  'Jaloliddin Masharipov': { position: 'MID', number: 10, birthYear: 1993 },
  'Otabek Shukurov': { position: 'MID', number: 6, birthYear: 1995 },
  'Azizbek Turgunboev': { position: 'MID', number: 14, birthYear: 2001 },
  'Dostonbek Khamdamov': { position: 'FWD', number: 11, birthYear: 2002 },
  'Eldor Shomurodov': { position: 'FWD', number: 9, birthYear: 1995 },
  'Igor Sergeev': { position: 'FWD', number: 7, birthYear: 1996 },
  'Abbos Fayzullaev': { position: 'FWD', number: 17, birthYear: 2005 },
  'Khusain Norchaev': { position: 'FWD', number: 19, birthYear: 2002 },
  'Nasimjon Khamroev': { position: 'MID', number: 16, birthYear: 2001 },
  'Abbosbek Fayzullaev': { position: 'FWD', number: 15, birthYear: 2004 },
  'Islom Tukhtakhodjaev': { position: 'DEF', number: 22, birthYear: 1997 },
  'Akmal Shorakhmedov': { position: 'MID', number: 18, birthYear: 1996 },
  'Bobur Abdikholikov': { position: 'DEF', number: 13, birthYear: 1996 },

  // ===== OFC =====

  // --- Nueva Zelanda ---
  'Stefan Marinovic': { position: 'GK', number: 1, birthYear: 1991 },
  'Michael Boxall': { position: 'DEF', number: 4, birthYear: 1988 },
  'Tim Payne': { position: 'DEF', number: 5, birthYear: 1990 },
  'Nando Pijnaker': { position: 'DEF', number: 3, birthYear: 1998 },
  'Liberato Cacace': { position: 'DEF', number: 2, birthYear: 2000 },
  'Joe Bell': { position: 'MID', number: 6, birthYear: 1999 },
  'Marko Stamenic': { position: 'MID', number: 8, birthYear: 2001 },
  'Matt Garbett': { position: 'MID', number: 14, birthYear: 2002 },
  'Alex Greive': { position: 'FWD', number: 11, birthYear: 2000 },
  'Chris Wood': { position: 'FWD', number: 9, birthYear: 1991 },
  'Ben Waine': { position: 'FWD', number: 17, birthYear: 2001 },
  'Sarpreet Singh': { position: 'MID', number: 10, birthYear: 1999 },
  'Callum McCowatt': { position: 'FWD', number: 7, birthYear: 1999 },
  'Kosta Barbarouses': { position: 'FWD', number: 15, birthYear: 1990 },
  'Elijah Just': { position: 'FWD', number: 19, birthYear: 1998 },
  'Jesse Randall': { position: 'FWD', number: 20, birthYear: 2004 },
  'Sam Sutton': { position: 'DEF', number: 22, birthYear: 1996 },
  'Francis de Vries': { position: 'MID', number: 18, birthYear: 2001 },
  'Logan Rogerson': { position: 'FWD', number: 16, birthYear: 1998 },

  // ===== REPECHAJE / PLAYOFF =====

  // --- Italia ---
  'Gianluigi Donnarumma': { position: 'GK', number: 1, birthYear: 1999 },
  'Giovanni Di Lorenzo': { position: 'DEF', number: 2, birthYear: 1993 },
  'Alessandro Bastoni': { position: 'DEF', number: 15, birthYear: 1999 },
  'Riccardo Calafiori': { position: 'DEF', number: 5, birthYear: 2002 },
  'Federico Dimarco': { position: 'DEF', number: 3, birthYear: 1997 },
  'Nicolo Barella': { position: 'MID', number: 23, birthYear: 1997 },
  'Sandro Tonali': { position: 'MID', number: 8, birthYear: 2000 },
  'Lorenzo Pellegrini': { position: 'MID', number: 10, birthYear: 1996 },
  'Davide Frattesi': { position: 'MID', number: 16, birthYear: 1999 },
  'Samuele Ricci': { position: 'MID', number: 6, birthYear: 2001 },
  'Nicolo Fagioli': { position: 'MID', number: 14, birthYear: 2001 },
  'Federico Chiesa': { position: 'FWD', number: 7, birthYear: 1997 },
  'Giacomo Raspadori': { position: 'FWD', number: 11, birthYear: 2000 },
  'Gianluca Scamacca': { position: 'FWD', number: 9, birthYear: 1999 },
  'Mateo Retegui': { position: 'FWD', number: 19, birthYear: 1999 },
  'Moise Kean': { position: 'FWD', number: 18, birthYear: 2000 },
  'Andrea Cambiaso': { position: 'DEF', number: 4, birthYear: 2000 },
  'Matteo Darmian': { position: 'DEF', number: 13, birthYear: 1989 },
  'Daniel Maldini': { position: 'FWD', number: 22, birthYear: 2001 },

  // --- Turquia ---
  'Altay Bayindir': { position: 'GK', number: 1, birthYear: 1998 },
  'Zeki Celik': { position: 'DEF', number: 2, birthYear: 1997 },
  'Merih Demiral': { position: 'DEF', number: 3, birthYear: 1998 },
  'Samet Akaydin': { position: 'DEF', number: 4, birthYear: 1994 },
  'Ferdi Kadioglu': { position: 'DEF', number: 5, birthYear: 1999 },
  'Hakan Calhanoglu': { position: 'MID', number: 10, birthYear: 1994 },
  'Kaan Ayhan': { position: 'DEF', number: 6, birthYear: 1994 },
  'Orkun Kokcu': { position: 'MID', number: 8, birthYear: 2000 },
  'Arda Guler': { position: 'MID', number: 14, birthYear: 2005 },
  'Yusuf Yazici': { position: 'MID', number: 7, birthYear: 1997 },
  'Kenan Yildiz': { position: 'FWD', number: 18, birthYear: 2005 },
  'Baris Alper Yilmaz': { position: 'FWD', number: 11, birthYear: 2000 },
  'Oguz Aydin': { position: 'FWD', number: 17, birthYear: 1999 },
  'Cenk Tosun': { position: 'FWD', number: 9, birthYear: 1991 },
  'Semih Kilicsoy': { position: 'FWD', number: 19, birthYear: 2005 },
  'Ismail Yuksek': { position: 'MID', number: 16, birthYear: 2000 },
  'Salih Ozcan': { position: 'MID', number: 15, birthYear: 1998 },
  'Kerem Akturkoglu': { position: 'FWD', number: 22, birthYear: 1998 },
  'Irfan Kahveci': { position: 'MID', number: 20, birthYear: 1995 },

  // --- Bolivia ---
  'Guillermo Viscarra': { position: 'GK', number: 1, birthYear: 1987 },
  'Jesus Sagredo': { position: 'DEF', number: 2, birthYear: 1998 },
  'Jose Sagredo': { position: 'DEF', number: 4, birthYear: 1995 },
  'Luis Haquin': { position: 'DEF', number: 3, birthYear: 1997 },
  'Roberto Fernandez': { position: 'DEF', number: 5, birthYear: 1991 },
  'Leonel Justiniano': { position: 'MID', number: 6, birthYear: 1992 },
  'Moises Villarroel': { position: 'MID', number: 8, birthYear: 1997 },
  'Fernando Saucedo': { position: 'MID', number: 14, birthYear: 1991 },
  'Ramiro Vaca': { position: 'MID', number: 10, birthYear: 1999 },
  'Erwin Saavedra': { position: 'MID', number: 7, birthYear: 1996 },
  'Henry Vaca': { position: 'MID', number: 11, birthYear: 1998 },
  'Marcelo Martins': { position: 'FWD', number: 9, birthYear: 1987 },
  'Carmelo Algaranaz': { position: 'FWD', number: 19, birthYear: 1993 },
  'Victor Abrego': { position: 'FWD', number: 17, birthYear: 1994 },
  'Rodrigo Ramallo': { position: 'FWD', number: 22, birthYear: 1992 },
  'Boris Cespedes': { position: 'MID', number: 16, birthYear: 1996 },
  'Miguel Terceros': { position: 'MID', number: 15, birthYear: 2004 },
  'Robson Matheus': { position: 'FWD', number: 20, birthYear: 1997 },
  'Roberto Dominguez': { position: 'MID', number: 18, birthYear: 2001 },

  // --- Irak ---
  'Jalal Hassan': { position: 'GK', number: 1, birthYear: 1987 },
  'Ahmed Ibrahim': { position: 'DEF', number: 2, birthYear: 1995 },
  'Ali Adnan': { position: 'DEF', number: 3, birthYear: 1993 },
  'Rebin Sulaka': { position: 'DEF', number: 4, birthYear: 1993 },
  'Sherko Kareem': { position: 'DEF', number: 5, birthYear: 1995 },
  'Ibrahim Bayesh': { position: 'MID', number: 6, birthYear: 1997 },
  'Amjad Attwan': { position: 'MID', number: 8, birthYear: 1994 },
  'Ali Jasim': { position: 'MID', number: 10, birthYear: 2003 },
  'Mohanad Ali': { position: 'FWD', number: 9, birthYear: 2000 },
  'Aymen Hussein': { position: 'FWD', number: 11, birthYear: 1996 },
  'Ali Al-Hamadi': { position: 'FWD', number: 7, birthYear: 2000 },
  'Justin Meram': { position: 'FWD', number: 14, birthYear: 1988 },
  'Alaa Abbas': { position: 'FWD', number: 19, birthYear: 1995 },
  'Mohammed Dawood': { position: 'MID', number: 15, birthYear: 1996 },
  'Ahmed Yasin': { position: 'MID', number: 17, birthYear: 1991 },
  'Safaa Hadi': { position: 'MID', number: 16, birthYear: 1992 },
  'Hussein Ali': { position: 'DEF', number: 22, birthYear: 1997 },
  'Durgham Ismail': { position: 'MID', number: 13, birthYear: 1996 },
  'Ahmad Dhurgham': { position: 'DEF', number: 20, birthYear: 1998 },

  // --- Jamaica ---
  'Andre Blake': { position: 'GK', number: 1, birthYear: 1990 },
  'Greg Leigh': { position: 'DEF', number: 3, birthYear: 1994 },
  'Damion Lowe': { position: 'DEF', number: 4, birthYear: 1993 },
  "Di'Shon Bernard": { position: 'DEF', number: 5, birthYear: 2000 },
  "Amari'i Bell": { position: 'DEF', number: 2, birthYear: 1994 },
  'Ravel Morrison': { position: 'MID', number: 10, birthYear: 1993 },
  'Bobby Decordova-Reid': { position: 'FWD', number: 7, birthYear: 1993 },
  'Kasey Palmer': { position: 'MID', number: 14, birthYear: 1996 },
  'Joel Latibeaudiere': { position: 'DEF', number: 6, birthYear: 2000 },
  'Leon Bailey': { position: 'FWD', number: 9, birthYear: 1997 },
  'Michail Antonio': { position: 'FWD', number: 11, birthYear: 1990 },
  'Shamar Nicholson': { position: 'FWD', number: 17, birthYear: 1997 },
  'Daniel Johnson': { position: 'MID', number: 8, birthYear: 1992 },
  'Demarai Gray': { position: 'FWD', number: 15, birthYear: 1996 },
  'Ethan Pinnock': { position: 'DEF', number: 13, birthYear: 1993 },
  'Kemar Roofe': { position: 'FWD', number: 19, birthYear: 1993 },
  'Raheem Sterling': { position: 'FWD', number: 22, birthYear: 1994 },
  'Miles Lewis-Mayfield': { position: 'DEF', number: 18, birthYear: 2002 },
  'Kaheim Dixon': { position: 'DEF', number: 20, birthYear: 2002 },

  // --- RD Congo ---
  'Lionel Mpasi': { position: 'GK', number: 1, birthYear: 1999 },
  'Chancel Mbemba': { position: 'DEF', number: 4, birthYear: 1994 },
  'Arthur Masuaku': { position: 'DEF', number: 3, birthYear: 1993 },
  'Ngonda Muzinga': { position: 'DEF', number: 5, birthYear: 1998 },
  'Glody Likonza': { position: 'MID', number: 8, birthYear: 2000 },
  'Samuel Moutoussamy': { position: 'MID', number: 6, birthYear: 1996 },
  'Gael Kakuta': { position: 'MID', number: 10, birthYear: 1991 },
  'Yannick Bolasie': { position: 'FWD', number: 7, birthYear: 1989 },
  'Cedric Bakambu': { position: 'FWD', number: 9, birthYear: 1991 },
  'Chancel Mangulu': { position: 'FWD', number: 11, birthYear: 2001 },
  'Silas Katompa': { position: 'FWD', number: 17, birthYear: 2001 },
  'Dieu-Merci Mbokani': { position: 'FWD', number: 20, birthYear: 1985 },
  'Fiston Mayele': { position: 'FWD', number: 14, birthYear: 1995 },
  'Meschak Elia': { position: 'FWD', number: 15, birthYear: 1997 },
  'Theo Bongonda': { position: 'FWD', number: 22, birthYear: 1995 },
  'Arsene Zola': { position: 'MID', number: 18, birthYear: 1999 },
  'Nathan Ngoy': { position: 'DEF', number: 2, birthYear: 2003 },
  'Arthur Kabath': { position: 'MID', number: 16, birthYear: 1998 },
  'Gaius Makouta': { position: 'MID', number: 19, birthYear: 1998 },
};

// Jugadores agrupados por equipo (mismos nombres que en seed.js, sin "Escudo")
export const TEAM_PLAYERS = {
  'Mexico': ['Guillermo Ochoa','Jorge Sanchez','Cesar Montes','Johan Vasquez','Jesus Gallardo','Edson Alvarez','Luis Chavez','Orbelin Pineda','Carlos Rodriguez','Luis Romo','Erick Sanchez','Hirving Lozano','Alexis Vega','Roberto Alvarado','Uriel Antuna','Diego Lainez','Raul Jimenez','Henry Martin','Santiago Gimenez'],
  'Estados Unidos': ['Matt Turner','Sergino Dest','Chris Richards','Miles Robinson','Antonee Robinson','Tyler Adams','Weston McKennie','Yunus Musah','Giovanni Reyna','Brenden Aaronson','Malik Tillman','Christian Pulisic','Timothy Weah','Josh Sargent','Ricardo Pepi','Folarin Balogun','Haji Wright','Johnny Cardoso','Luca de la Torre'],
  'Canada': ['Maxime Crepeau','Alistair Johnston','Kamal Miller','Moise Bombito','Sam Adekugbe','Stephen Eustaquio','Ismael Kone','Mark-Anthony Kaye','Tajon Buchanan','Jonathan David','Alphonso Davies','Cyle Larin','Liam Millar','Junior Hoilett','Richie Laryea','Jonathan Osorio','Jacob Shaffelburg','Samuel Piette','Theo Corbeanu'],
  'Panama': ['Orlando Mosquera','Michael Murillo','Fidel Escobar','Andres Andrade','Eric Davis','Adalberto Carrasquilla','Cristian Martinez','Jose Luis Rodriguez','Edgar Barcenas','Alberto Quintero','Freddy Gondola','Jose Fajardo','Rolando Blackburn','Cesar Yanis','Ivan Anderson','Anibal Godoy','Ernesto Walker','Jiovany Ramos','Eduardo Guerrero'],
  'Haiti': ['Alexandre Duval','Frantzdy Pierrot','Carlens Arcus','Kevin LaFrance','Ricardo Ade','Derrick Etienne Jr','Melchie Dumornay','Bryan Alceus','Duckens Nazon','Leverton Pierre','Danny Duval','Stephane Lambese','Alex Jr Christian','Ronaldo Damus','Owayne Gordon','Jean-Ricner Bellegarde','Steeven Saba','Zachary Herivaux','Danley Jean Jacques'],
  'Curazao': ['Eloy Room','Juninho Bacuna','Cuco Martina','Darryl Lachman','Shermaine Martina','Leandro Bacuna','Michaell Tirpijn','Kenji Gorre','Elson Hooi','Rangelo Janga','Brandley Kuwas','Gervane Kastaneer','Jairzinho Pieter','Charlison Benschop','Jurien Gaari','Vurnon Anita','Shadrach Victora','Quenten Martinus','Jeremy de Nooijer'],
  'Argentina': ['Emiliano Martinez','Nahuel Molina','Cristian Romero','Nicolas Otamendi','Nicolas Tagliafico','Rodrigo De Paul','Leandro Paredes','Enzo Fernandez','Alexis Mac Allister','Giovani Lo Celso','Exequiel Palacios','Lionel Messi','Lautaro Martinez','Julian Alvarez','Paulo Dybala','Alejandro Garnacho','Nicolas Gonzalez','Thiago Almada','Giuliano Simeone'],
  'Brasil': ['Alisson','Danilo','Marquinhos','Gabriel Magalhaes','Alex Telles','Casemiro','Bruno Guimaraes','Lucas Paqueta','Andre','Joao Gomes','Douglas Luiz','Vinicius Jr','Raphinha','Rodrygo','Richarlison','Endrick','Gabriel Martinelli','Savinho','Estevao'],
  'Colombia': ['Camilo Vargas','Daniel Munoz','Davinson Sanchez','Yerry Mina','Johan Mojica','Wilmar Barrios','Mateus Uribe','James Rodriguez','Richard Rios','Jefferson Lerma','Kevin Castaño','Luis Diaz','Rafael Santos Borre','Luis Sinisterra','Jhon Cordoba','Miguel Borja','Jhon Arias','Jorge Carrascal','Juan Camilo Portilla'],
  'Ecuador': ['Hernan Galindez','Angelo Preciado','Felix Torres','Piero Hincapie','Pervis Estupinan','Moises Caicedo','Carlos Gruezo','Alan Franco','Kendry Paez','Jeremy Sarmiento','Gonzalo Plata','Enner Valencia','Michael Estrada','Kevin Rodriguez','John Yeboah','Willian Pacho','Jose Cifuentes','Angel Mena','Joao Rojas'],
  'Paraguay': ['Carlos Coronel','Alberto Espinola','Gustavo Gomez','Omar Alderete','Junior Alonso','Andres Cubas','Mathias Villasanti','Miguel Almiron','Julio Enciso','Matias Rojas','Ramon Sosa','Angel Romero','Antonio Sanabria','Adam Bareiro','Gabriel Avalos','Alex Arce','Fabian Balbuena','Damian Bobadilla','Hernan Perez'],
  'Uruguay': ['Sergio Rochet','Nahitan Nandez','Jose Maria Gimenez','Ronald Araujo','Mathias Olivera','Federico Valverde','Rodrigo Bentancur','Manuel Ugarte','Nicolas De La Cruz','Giorgian De Arrascaeta','Facundo Pellistri','Darwin Nunez','Luis Suarez','Maximiliano Araujo','Agustin Canobbio','Facundo Torres','Matias Viña','Sebastian Caceres','Brian Rodriguez'],
  'Francia': ['Mike Maignan','Jules Kounde','Dayot Upamecano','William Saliba','Theo Hernandez',"N'Golo Kante",'Aurelien Tchouameni','Eduardo Camavinga','Antoine Griezmann','Adrien Rabiot','Youssouf Fofana','Kylian Mbappe','Ousmane Dembele','Marcus Thuram','Randal Kolo Muani','Bradley Barcola','Warren Zaire-Emery','Michael Olise','Khephren Thuram'],
  'Alemania': ['Manuel Neuer','Joshua Kimmich','Antonio Rudiger','Nico Schlotterbeck','David Raum','Robert Andrich','Pascal Gross','Jamal Musiala','Florian Wirtz','Leon Goretzka','Aleksandar Pavlovic','Leroy Sane','Serge Gnabry','Kai Havertz','Niclas Fullkrug','Chris Fuhrich','Maximilian Beier','Deniz Undav','Benjamin Henrichs'],
  'Espana': ['Unai Simon','Dani Carvajal','Aymeric Laporte','Robin Le Normand','Marc Cucurella','Rodri','Pedri','Gavi','Dani Olmo','Fabian Ruiz','Mikel Merino','Lamine Yamal','Nico Williams','Alvaro Morata','Ferran Torres','Alejandro Balde','Fermin Lopez','Mikel Oyarzabal','Pau Cubarsi'],
  'Inglaterra': ['Jordan Pickford','Kyle Walker','John Stones','Marc Guehi','Luke Shaw','Declan Rice','Jude Bellingham','Kobbie Mainoo','Phil Foden','Cole Palmer','Angel Gomes','Bukayo Saka','Anthony Gordon','Harry Kane','Ollie Watkins','Morgan Gibbs-White','Trent Alexander-Arnold','Jarrod Bowen','Noni Madueke'],
  'Portugal': ['Diogo Costa','Joao Cancelo','Ruben Dias','Antonio Silva','Nuno Mendes','Bruno Fernandes','Vitinha','Bernardo Silva','Joao Felix','Joao Palhinha','Joao Neves','Cristiano Ronaldo','Rafael Leao','Goncalo Ramos','Diogo Jota','Pedro Neto','Francisco Conceicao','Goncalo Inacio','Renato Sanches'],
  'Paises Bajos': ['Bart Verbruggen','Denzel Dumfries','Virgil van Dijk','Nathan Ake','Ian Maatsen','Frenkie de Jong','Ryan Gravenberch','Tijjani Reijnders','Xavi Simons','Teun Koopmeiners','Jerdy Schouten','Cody Gakpo','Donyell Malen','Memphis Depay','Brian Brobbey','Joshua Zirkzee','Micky van de Ven','Jurrien Timber','Jeremie Frimpong'],
  'Belgica': ['Koen Casteels','Timothy Castagne','Wout Faes','Jan Vertonghen','Arthur Theate','Kevin De Bruyne','Amadou Onana','Youri Tielemans','Arne Engels','Orel Mangala','Charles De Ketelaere','Jeremy Doku','Lois Openda','Romelu Lukaku','Leandro Trossard','Johan Bakayoko','Dodi Lukebakio','Zeno Debast','Aster Vranckx'],
  'Croacia': ['Dominik Livakovic','Josip Stanisic','Josko Gvardiol','Duje Caleta-Car','Borna Sosa','Luka Modric','Mateo Kovacic','Marcelo Brozovic','Mario Pasalic','Lovro Majer','Martin Baturina','Ivan Perisic','Ante Budimir','Andrej Kramaric','Bruno Petkovic','Luka Sucic','Igor Matanovic','Josip Sutalo','Marin Pongracic'],
  'Suiza': ['Yann Sommer','Silvan Widmer','Manuel Akanji','Nico Elvedi','Ricardo Rodriguez','Granit Xhaka','Denis Zakaria','Remo Freuler','Xherdan Shaqiri','Ruben Vargas','Fabian Rieder','Dan Ndoye','Breel Embolo','Zeki Amdouni','Noah Okafor','Steven Zuber','Edimilson Fernandes','Ardon Jashari','Filip Ugrinic'],
  'Austria': ['Patrick Pentz','Stefan Posch','Kevin Danso','Maximilian Wober','Phillipp Mwene','Konrad Laimer','Nicolas Seiwald','Florian Grillitsch','Marcel Sabitzer','Christoph Baumgartner','Romano Schmid','Marko Arnautovic','Michael Gregoritsch','Kevin Stöger','Patrick Wimmer','Matthias Seidl','Flavius Daniliuc','Phillipp Lienhart','Alexander Prass'],
  'Escocia': ['Angus Gunn','Anthony Ralston','Grant Hanley','John Souttar','Andrew Robertson','Scott McTominay','Callum McGregor','Billy Gilmour','John McGinn','Kenny McLean','Ryan Christie','Che Adams','Lyndon Dykes','Lawrence Shankland','Ben Doak','James Forrest','Ryan Jack','Andy Irving','Lewis Morgan'],
  'Noruega': ['Orjan Nyland','Marcus Holmgren Pedersen','Leo Ostigard','Andreas Hanche-Olsen','Birger Meling','Martin Odegaard','Sander Berge','Fredrik Aursnes','Antonio Nusa','Oscar Bobb','Jens Petter Hauge','Erling Haaland','Alexander Sorloth','Joshua King','Mohamed Elyounoussi','David Moller Wolfe','Patrick Berg','Morten Thorsby','Julian Ryerson'],
  'Marruecos': ['Yassine Bounou','Achraf Hakimi','Nayef Aguerd','Romain Saiss','Noussair Mazraoui','Sofyan Amrabat','Azzedine Ounahi','Hakim Ziyech','Youssef En-Nesyri','Ilias Akhomach','Bilal El Khannouss','Brahim Diaz','Abde Ezzalzouli','Soufiane Rahimi','Amine Harit','Munir El Haddadi','Zakaria Aboukhlal','Adam Aznou','Eliesse Ben Seghir'],
  'Senegal': ['Edouard Mendy','Kalidou Koulibaly','Abdou Diallo','Youssouf Sabaly','Formose Mendy','Idrissa Gueye','Nampalys Mendy','Pape Matar Sarr','Krepin Diatta','Ismaila Sarr','Iliman Ndiaye','Nicolas Jackson','Sadio Mane','Habib Diarra','Boulaye Dia','Lamine Camara','Mikayil Faye','El Hadji Malick Diouf','Cherif Ndiaye'],
  'Egipto': ['Mohamed El Shenawy','Ahmed Fatouh','Mohamed Abdel-Moneim','Mahmoud Hamdy','Ahmed Hegazi','Mohamed Elneny','Tarek Hamed','Emam Ashour','Ibrahim Adel','Mahmoud Trezeguet','Mostafa Mohamed','Mohamed Salah','Omar Marmoush','Ahmed Koka','Marwan Hamdi','Hussein El Shahat','Karim Fouad','Mohamed Sherif','Ahmed Sayed Zizo'],
  'Ghana': ['Lawrence Ati-Zigi','Tariq Lamptey','Mohammed Salisu','Alexander Djiku','Gideon Mensah','Thomas Partey','Mohammed Kudus','Elisha Owusu','Antoine Semenyo','Ibrahim Sulemana','Fatawu Issahaku','Jordan Ayew','Inaki Williams','Ernest Nuamah','Abdul Samed','Osman Bukari','Kamaldeen Sulemana','Jerome Opoku','Edmund Addo'],
  'Costa de Marfil': ['Yahia Fofana','Serge Aurier','Odilon Kossounou','Willy Boly','Ghislain Konan','Franck Kessie','Seko Fofana','Ibrahim Sangare','Jean-Philippe Krasso','Nicolas Pepe','Sebastien Haller','Simon Adingra','Oumar Diakite','Karim Konate','Christian Kouame','Max-Alain Gradel','Wilfried Singo','Evan Ndicka','Jeremie Boga'],
  'Sudafrica': ['Ronwen Williams','Khuliso Mudau','Siyanda Xulu','Mothobi Mvala','Aubrey Modiba','Teboho Mokoena','Themba Zwane','Ethan Brooks','Elias Mokwana','Percy Tau','Lyle Foster','Iqraam Rayners','Evidence Makgopa','Oswin Appollis','Bathusi Aubaas','Thalente Mbatha','Relebohile Mofokeng','Rushwin Dortley','Patrick Maswanganyi'],
  'Tunez': ['Aymen Dahmen','Mohamed Drager','Yassine Meriah','Montassar Talbi','Ali Abdi','Aissa Laidouni','Ellyes Skhiri','Hannibal Mejbri','Youssef Msakni','Naim Sliti','Saifeddine Jaziri','Anis Ben Slimane','Issam Jebali','Seifeddine Jaziri','Mohamed Ali Ben Romdhane','Ferjani Sassi','Ali Maaloul','Wajdi Kechrida','Ghaylane Chaalali'],
  'Argelia': ['Rais M\'Bolhi','Youcef Atal','Aissa Mandi','Abdelkader Bedrane','Ramy Bensebaini','Ismael Bennacer','Nabil Bentaleb','Hichem Boudaoui','Amine Gouiri','Said Benrahma','Riyad Mahrez','Islam Slimani','Baghdad Bounedjah','Yacine Brahimi','Andy Delort','Mohamed Amoura','Adam Ounas','Ibrahim Maza','Farhi Amine'],
  'Cabo Verde': ['Vozinha','Steven Fortes','Roberto Lopes','Logan Costa','Dylan Tavares','Kenny Rocha Santos','Jamiro Monteiro','Nuno Borges','Ryan Mendes','Garry Rodrigues','Julio Tavares','Lisandro Semedo','Gilson Benchimol','Jovane Cabral','Patrick Andrade','Willy Semedo','Djaniny','Bebeto','Stopira'],
  'Japon': ['Zion Suzuki','Hiroki Sakai','Ko Itakura','Takehiro Tomiyasu','Miki Yamane','Wataru Endo','Hidemasa Morita','Daichi Kamada','Takefusa Kubo','Ritsu Doan','Kaoru Mitoma','Takumi Minamino','Ayase Ueda','Kyogo Furuhashi','Daizen Maeda','Ao Tanaka','Keito Nakamura','Koji Miyoshi','Yuki Soma'],
  'Corea del Sur': ['Kim Seung-gyu','Kim Moon-hwan','Kim Min-jae','Kim Young-gwon','Kim Jin-su','Hwang In-beom','Jung Woo-young','Lee Jae-sung','Lee Kang-in','Hwang Hee-chan','Son Heung-min','Cho Gue-sung','Lee Seung-woo','Bae Jun-ho','Jeong Sang-bin','Hong Hyun-seok','Park Yong-woo','Oh Hyeon-gyu','Yang Hyun-jun'],
  'Australia': ['Mathew Ryan','Nathaniel Atkinson','Harry Souttar','Kye Rowles','Aziz Behich','Jackson Irvine','Aaron Mooy','Cameron Devlin','Riley McGree','Craig Goodwin','Keanu Baccus','Mitch Duke','Jamie Maclaren','Kusini Yengi','Garang Kuol','Marco Tilio','Aiden O\'Neill','Connor Metcalfe','Martin Boyle'],
  'Arabia Saudita': ['Mohammed Al Owais','Sultan Al-Ghanam','Ali Al-Bulayhi','Abdulelah Al-Amri','Yasser Al-Shahrani','Mohamed Kanno','Abdulellah Al-Malki','Saud Abdulhamid','Salem Al-Dawsari','Firas Al-Buraikan','Abdullah Al-Hamdan','Saleh Al-Shehri','Nasser Al-Dawsari','Nawaf Al-Abed','Hassan Al-Tambakti','Ali Al-Hassan','Ayman Yahya','Abdullah Madu','Turki Al-Ammar'],
  'Iran': ['Alireza Beiranvand','Sadegh Moharrami','Morteza Pouraliganji','Shoja Khalilzadeh','Ehsan Hajsafi','Saeid Ezatolahi','Ahmad Nourollahi','Ali Gholizadeh','Mehdi Taremi','Sardar Azmoun','Alireza Jahanbakhsh','Karim Ansarifard','Ali Karimi','Omid Noorafkan','Milad Sarlak','Allahyar Sayyadmanesh','Mehdi Ghayedi','Vahid Amiri','Rouzbeh Cheshmi'],
  'Catar': ['Saad Al Sheeb','Pedro Miguel','Bassam Al-Rawi','Abdelkarim Hassan','Homam Ahmed','Hassan Al-Haydos','Karim Boudiaf','Abdulaziz Hatem','Akram Afif','Almoez Ali','Mohammed Muntari','Ismaeel Mohammad','Yusuf Abdurisag','Musab Kheder','Ahmed Alaaeldin','Assim Madibo','Sultan Al-Brake','Ali Asad','Hashim Ali'],
  'Jordania': ['Yazeed Abulaila','Salem Al-Ajalin','Anas Bani-Yaseen','Abdallah Nasib','Ehsan Haddad','Baha Faisal','Nizar Al-Rashdan','Mousa Al-Taamari','Yazan Al-Naimat','Hamza Al-Dardour','Musa Mustafa','Ali Olwan','Ahmad Ersan','Oday Dabbagh','Tareq Khattab','Mahmoud Mardi','Youssef Rawashdeh','Mohammed Abu Zraiq','Amer Shafi'],
  'Uzbekistan': ['Utkir Yusupov','Husniddin Aliqulov','Abdukodir Khusanov','Jermejev Nurmatov','Davron Khashimov','Oston Urunov','Jaloliddin Masharipov','Otabek Shukurov','Azizbek Turgunboev','Dostonbek Khamdamov','Eldor Shomurodov','Igor Sergeev','Abbos Fayzullaev','Khusain Norchaev','Nasimjon Khamroev','Abbosbek Fayzullaev','Islom Tukhtakhodjaev','Akmal Shorakhmedov','Bobur Abdikholikov'],
  'Nueva Zelanda': ['Stefan Marinovic','Michael Boxall','Tim Payne','Nando Pijnaker','Liberato Cacace','Joe Bell','Marko Stamenic','Matt Garbett','Alex Greive','Chris Wood','Ben Waine','Sarpreet Singh','Callum McCowatt','Kosta Barbarouses','Elijah Just','Jesse Randall','Sam Sutton','Francis de Vries','Logan Rogerson'],
  'Italia': ['Gianluigi Donnarumma','Giovanni Di Lorenzo','Alessandro Bastoni','Riccardo Calafiori','Federico Dimarco','Nicolo Barella','Sandro Tonali','Lorenzo Pellegrini','Davide Frattesi','Samuele Ricci','Nicolo Fagioli','Federico Chiesa','Giacomo Raspadori','Gianluca Scamacca','Mateo Retegui','Moise Kean','Andrea Cambiaso','Matteo Darmian','Daniel Maldini'],
  'Turquia': ['Altay Bayindir','Zeki Celik','Merih Demiral','Samet Akaydin','Ferdi Kadioglu','Hakan Calhanoglu','Kaan Ayhan','Orkun Kokcu','Arda Guler','Yusuf Yazici','Kenan Yildiz','Baris Alper Yilmaz','Oguz Aydin','Cenk Tosun','Semih Kilicsoy','Ismail Yuksek','Salih Ozcan','Kerem Akturkoglu','Irfan Kahveci'],
  'Bolivia': ['Guillermo Viscarra','Jesus Sagredo','Jose Sagredo','Luis Haquin','Roberto Fernandez','Leonel Justiniano','Moises Villarroel','Fernando Saucedo','Ramiro Vaca','Erwin Saavedra','Henry Vaca','Marcelo Martins','Carmelo Algaranaz','Victor Abrego','Rodrigo Ramallo','Boris Cespedes','Miguel Terceros','Robson Matheus','Roberto Dominguez'],
  'Irak': ['Jalal Hassan','Ahmed Ibrahim','Ali Adnan','Rebin Sulaka','Sherko Kareem','Ibrahim Bayesh','Amjad Attwan','Ali Jasim','Mohanad Ali','Aymen Hussein','Ali Al-Hamadi','Justin Meram','Alaa Abbas','Mohammed Dawood','Ahmed Yasin','Safaa Hadi','Hussein Ali','Durgham Ismail','Ahmad Dhurgham'],
  'Jamaica': ['Andre Blake','Greg Leigh','Damion Lowe',"Di'Shon Bernard","Amari'i Bell",'Ravel Morrison','Bobby Decordova-Reid','Kasey Palmer','Joel Latibeaudiere','Leon Bailey','Michail Antonio','Shamar Nicholson','Daniel Johnson','Demarai Gray','Ethan Pinnock','Kemar Roofe','Raheem Sterling','Miles Lewis-Mayfield','Kaheim Dixon'],
  'RD Congo': ['Lionel Mpasi','Chancel Mbemba','Arthur Masuaku','Ngonda Muzinga','Glody Likonza','Samuel Moutoussamy','Gael Kakuta','Yannick Bolasie','Cedric Bakambu','Chancel Mangulu','Silas Katompa','Dieu-Merci Mbokani','Fiston Mayele','Meschak Elia','Theo Bongonda','Arsene Zola','Nathan Ngoy','Arthur Kabath','Gaius Makouta'],
};
